### ISSUE TITLE
[Discussion] Plugin ideas

### ISSUE THREAD

**Issue by KELiON** [cerebroapp/cerebro#112]
* If you have an idea for plugin – post it here;
* If you are a developer and want to pick an idea and implement it – notice everyone here.

**Comment by maximbaz** [comment]
**Idea:** Getting current local time, date and timezone by searching `time in madrid`. Google's output:

```
4:58 PM
Tuesday, February 14, 2017 (GMT+1)
Time in Madrid, Spain
```

**Comment by KELiON** [comment]
@maximbaz btw, I've already started to work on that: 

![screen shot 2017-02-14 at 23 27 39](https://cloud.githubusercontent.com/assets/594298/22952432/4dca5d74-f30d-11e6-9369-4cbbc30805d6.png)

I'll publish it soon. I think after some polishing it will be enough for first version, later I wanted to show in preview something like [worldtimebuddy](http://www.worldtimebuddy.com/) do

<img width="1092" alt="screen shot 2017-02-14 at 23 30 32" src="https://cloud.githubusercontent.com/assets/594298/22952492/99b826a8-f30d-11e6-8472-345681f6c318.png">

**Comment by maximbaz** [comment]
That is so cool! I'd like to suggest to write the time directly in the search box, just like the convertor plugin does, in gray text. That way I get the most important information without even moving my eyes from the search box. Something like that, what do you think?

![image](https://cloud.githubusercontent.com/assets/1177900/22953201/7d000cb2-f310-11e6-8a32-89eed21838d5.png)

**Comment by KELiON** [comment]
@maximbaz first version is timezones is [here](https://github.com/kelion/cerebro-timezones), any ideas improvements are welcome)

**Comment by maximbaz** [comment]
I love it :heart: 🕗

A small idea: what do you think about treating `time` and/or `time now` in a special way, and showing the time in the current location? Or there is no reliable way to tell the current location?

Now when I type `time now`, I see Toronto time :)

**Comment by KELiON** [comment]
@maximbaz why do you use Cerebro to see current time, not just OS clock?

**Comment by maximbaz** [comment]
I was testing the plugin by entering different values, one of the values was "now" and I was surprised to see Toronto instead of nothing :) 

I have no arguments to support this idea :)

**Comment by elis** [comment]
`my` - search everything I have on connected apps - facebook, google, emails, docs, etc' etc' etc'

**Comment by ch3ckmat3** [comment]
is local file search coming for windows (designated folders)?

**Comment by KELiON** [comment]
In #45 @reflog mentioned that he started to work on windows search [plugin](https://github.com/reflog/cerebro-plugin-everything), but he was stuck with some problem, so now we just need someone who can help him to resolve it

**Comment by Zenohm** [comment]
The ability to search and retreive the first paragraph or so of Wikipedia entries as well as the primary Wolfram Alpha results (Which can be fetched extremely easily through their plugin. [See here for all the APIs that Wolfram Alpha provides publicly](http://products.wolframalpha.com/api/), and [here for the one that would be the easiest to implement and theme](http://products.wolframalpha.com/simple-api/documentation/)). With just the Wolfram Alpha plugin alone, this system would be made vastly more powerful and useful. On top of that, the results can be themed to fit in with the launcher ([See here](http://products.wolframalpha.com/simple-api/documentation/img/foreground.png)).

**Comment by Lampwick** [comment]
define using Gnome Dictionary for linux.
Likewise contacts search using Gnome Contacts.

**Comment by maximbaz** [comment]
Perhaps extension of the converter plugin: convert datetime to unix timestamp and back.

**Comment by ColCh** [comment]
other one is to use multitran for translating instead of yandex http://www.multitran.ru/c/m.exe?a=1
I can work on this plugin since I want it too much :)

**Comment by rafa-acioly** [comment]
Hey guys! i just finished the first version of color convert (rgb to hex and vice versa), i'm currently needing of help to make a implementation of "copy to clipboard" and show the result on "main section" of cerebro, I'll be happy if someone sends the pull request.

https://github.com/rafa-acioly/cerebro-convertcolor

hope you all enjoy.

**Comment by elmerehbi** [comment]
+1 for [Wikipedia & WolframAlpha](https://github.com/KELiON/cerebro/issues/112#issuecomment-281575675)

**Comment by Banterlmanchild** [comment]
Search in software centre/app store for apps not installed

**Comment by srdeleon** [comment]
Plugin that announces new released or featured plugins.

**Comment by srdeleon** [comment]
Plugin to make quick reminders on the fly.

**Comment by Kwaadpepper** [comment]
Zeal integration
Steam Games
Virtualbox Machines

**Comment by dynobo** [comment]
* File Search
* Calculator
* Search for Contacts (CardDAV)
* Weather forecast

**Comment by Banterlmanchild** [comment]
Weather updates based by default on your location but if you put a place before hand then weather there, could be merged with the time

**Comment by Banterlmanchild** [comment]
Dictionary and thesaurus native support would be pretty cool

**Comment by flavioheleno** [comment]
Hey all, I just put together a very simple plugin for searching [php.net](http://php.net) manual.

It is here: https://github.com/flavioheleno/cerebro-php

Whenever I have some more time to hack into it, I want to get the results to be displayed inside Cerebro, just like the [stackoverflow](https://github.com/KELiON/cerebro-stackoverflow) plugin does.

**Comment by yuzugit** [comment]
Hey all, nice tool (I switch from Wox to this one). I think it could be very could to be able to select search engine in the tool parameters. I though about using plugins but if I don't want google as a search engine at all it's not possible unless I recompile from the source.

Having a list of "favorite" search engine could be nice (wikipedia, duckduckgo, qwant...) like in firefox params.

**Comment by gautierdag** [comment]
A Spotify control and search plugin would be cool.

**Comment by masterperas** [comment]
following @reflog i made a small plugin to allow for full search on windows environment, it works through Everything CLI by voidtools https://github.com/masterperas/es-everything-plugin

**Comment by ch3ckmat3** [comment]
A plugin based on [http://www.filechef.com/](http://www.filechef.com/) search formulas...

**Comment by KELiON** [comment]
@flavioheleno maybe you want to try [cerebro-devdocs](https://github.com/KELiON/cerebro-devdocs) plugin, that uses https://devdocs.io/. PHP documentation is also available there

**Comment by flavioheleno** [comment]
cool @KELiON, I'll check it. My idea around [cerebro-php](https://github.com/flavioheleno/cerebro-php) is to render the doc right in the display, making it handy for a quick check, but I'm quite far from that at this point :-)

**Comment by KELiON** [comment]
@flavioheleno so, you'll like devdocs plugin:) 

![screen shot 2017-03-01 at 15 10 14](https://cloud.githubusercontent.com/assets/594298/23463290/3d0cd860-fe91-11e6-8fcb-486023a602f9.png)

**Comment by flavioheleno** [comment]
ha! that's **exactly** what I wanted! brilliant @KELiON! I'm gonna ditch my plugin and move over to that one :-D

**Comment by tim-hm** [comment]
I would love to see an Evernote plugin which let's you search your notes and quickly add new ones.

**Comment by grvrulz** [comment]
It would be great to have a snippets plugin like Alfred
https://www.alfredapp.com/help/features/snippets/

**Comment by Lampwick** [comment]
How about integration of the [Jarvis](https://github.com/sukeesh/Jarvis) Personal assistant?
[Jarvis demo video](https://www.youtube.com/watch?v=PR-nxqmG3V8)

**Comment by glja021** [comment]
I could help writing plugins for Linux, been wanting to contribute to this project for a while.
I'd like to see implemented 
- File search 
- Define a word
- Jarvis integration looks interesting

**Comment by valdotdev** [comment]
A proper (native) file search would be nice with configurable directories and/or volumes on macOS

**Comment by NonlinearFruit** [comment]
**Fuzzy search** (at least on applications) defined as each result contains the letters of the query in order but not necessarily in consecutively. For example, `vd` would match `Vivaldi`.

**Comment by janekkkk** [comment]
**Theme colour** 

Change colour of the Cerebro window based on the Windows / GTK theme or whatever.

**Comment by janekkkk** [comment]
** Simplenote integration **

[Simplenote](https://simplenote.com/) has become my go-to note taking app because it's open-source and supports all devices I have running (iOS, Android, Mac, Windows, Linux,). Searching for notes would be a great feature.

**Comment by rafa-acioly** [comment]
@janekkkk 
> https://simplenote.com/developers/

**Comment by janekkkk** [comment]
@rafa-acioly Thanks for letting me know this is impossible at the moment.

"The current version of the Simperium API does not allow for 3rd party development of Simplenote apps at this time. We will update this page in the future after we add support. Thanks for your interest!" 👎 

So forget about my Simplenote idea for now.

**Comment by Tim3game** [comment]
**JavaDocs integration**

The possibility to add javadocs documentations from only a URL/Search term.

**Comment by renatoosousa** [comment]
I'd like to see implemented
* real time score of a lot of sports and esports

**Comment by horizon0708** [comment]
@Kwaadpepper check out [cerezeal](https://github.com/horizon0708/cerezeal) for quick zeal searches with custom shorthand support :)

**Comment by Ftamino** [comment]
I would like it more with a Ecoisa search

**Comment by dubisdev** [comment]
> I would like it more with a Ecoisa search

Hope this helps
https://github.com/dubisdev/cerebro-ecosia

**Comment by httpsWina** [comment]
the ability to launch games from multiple launchers such as epic games, steam or gog.
the only extension that did this is no longer working and worked only for steam and windows (https://github.com/Wolvan/cerebro-steamlaunch).

**Comment by kskollepara** [comment]
Would be nice to have:
1. A plugin to search through firefox (or default browser) history. I currently use a [plugin on Ulauncher](https://github.com/rmassidda/ulauncher-firefox-history).
2. As mentioned before, ability to search in websites like Wikipedia, Stackoverflow, youtube, etc. In Ulauncher I can do this by adding so-called shortcuts (see image below), but it would be cooler if there was an auto suggest feature like in firefox search shortcuts.
![image](https://user-images.githubusercontent.com/24797363/227537574-6a812ef2-4881-4264-8311-e04ca83dbd3d.png)

**Comment by oguhpereira** [comment]
I will close this discussion issue so we can start using the new github discussion tool
