### ISSUE TITLE
plugin installation don't work

### ISSUE THREAD

**Issue by letroll** [cerebroapp/cerebro#125]
the installation of a plugin is blocked on the loading window.
I think that this is the proxy of the company. I have set my environment variables http_proxy and https_proxy, but that doesn't help ....
I was able to install plugins on previous versions, I'm currently in 0.2.6

**Comment by KELiON** [comment]
@letroll did you use proxies in previous versions?

**Comment by letroll** [comment]
Yes and I think with the same settings but I'm not sure about 100%

**Comment by letroll** [comment]
after somes tests, I can confirm, no problem with versions 0.2.4 and 0.2.5. So 0.2.6 has a regression I think

**Comment by KELiON** [comment]
@letroll can you try to do next, please?

1) Open Cerebro preferences
2) Turn on developer mode and show in menu bar
3) In tray menu select developer → Dev. Tools (main) → switch to "console"
4) Select in tray menu developer → Reload
6) Try to install any plugin
7) Share output of your console here

**Comment by toXel** [comment]
I have the same problems and I walked through the steps. This is the output:

```
[npm] Install package cerebro-windows-system
main.bundle.js:26459 Version: 0.1.2
main.bundle.js:26418 Extract https://registry.npmjs.org/cerebro-windows-system/-/cerebro-windows-system-0.1.2.tgz to C:\Users\timo.arlt\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-windows-system
events.js:160 Uncaught Error: connect ETIMEDOUT 151.101.112.162:443exports._errnoException @ util.js:1026exports._exceptionWithHostPort @ util.js:1049afterConnect @ net.js:1081
events.js:160 Uncaught Error: socket hang up
```

**Comment by KELiON** [comment]
@toXel do you also use proxy?

**Comment by toXel** [comment]
Yes. And I can install npm packages without problems.

**Comment by KELiON** [comment]
@toXel ok, than it is clear. Thanks!

**Comment by exislow** [comment]
I have the same problem. Is it possible to fix this?

**Comment by letroll** [comment]
Same here I can install npm packages without problems.

**Comment by gaursagar** [comment]
+1 Can't install plugins behind proxy. Manual installation works, but isn't very convenient.

**Comment by letroll** [comment]
@gaursagar can share an example of manual installation?

**Comment by gaursagar** [comment]
@letroll
Assuming you have a working installation of `npm`, to install a plugin for instance `cerebro-wiki`:
1. Go to `~/.config/Cerebro/plugins`
2. `npm install cerebro-wiki`

Done :)

**Comment by letroll** [comment]
when I want manage plugin I have the following error:

https://registry.npmjs.com/-/v1/search?from=0&size=500&text=keywords:cerebro-plugin,cerebro-extracted-plugin Failed to load resource: the server responded with a status of 407 (Proxy Authentication Required)

**Comment by KELiON** [comment]
@letroll looks like you're also using proxy, so try to install the plugin using npm see messages above for instructions)

**Comment by oguhpereira** [comment]
I'm closing, understanding that it has been resolved, any questions can reopen again

Thanks @gaursagar by support
