### ISSUE TITLE
Active screen

### ISSUE THREAD

**Issue by luisdavim** [cerebroapp/cerebro#131]
I use a multi-head setup and cerebro always starts on the main screen (usually the laptop's built in monitor) it would be great if cerebro could be displayed on the active monitor, it could either follow the mouse or the window that has focus.

**Comment by maximbaz** [comment]
This feature was implemented a while ago, and it works fine for me on Linux. I know @KELiON also tested on his Mac. Maybe you discovered a bug. But first, what OS do you use? Do you have the latest version installed?

**Comment by luisdavim** [comment]
I'm on macOS Sierra 10.12.3 running cerebro 0.2.6 that I installed with brew cask.

**Comment by matmunn** [comment]
I'm on macOS 10.12.4 running Cerebro 0.2.5 installed from the .dmg on the releases page and I can confirm that I only get the cerebro window on my main monitor.

**Comment by maximbaz** [comment]
Guys I've just realized that I misread the description, sorry! The feature I mentioned was about _remembering_ the window position, instead of being always displayed on the primary screen. That is, if you move a window to a different screen, next time it will start there. But unfortunately there is no electron API to detect the _active_ screen, or I didn't find one.

**Comment by matmunn** [comment]
In that case I can confirm that it remembers the active screen on macOS 10.12.4 ;)

**Comment by luisdavim** [comment]
Hi,
Sorry if I didn't expressed myself correctly. 
I never used electron so this may be rubbish but I think you could use '''screen.getCursorScreenPoint()''' to get the cursor position and then '''screen.getDisplayNearestPoint(point)''' to get the display does that makes sense? 

https://github.com/electron/electron/blob/master/docs/api/screen.md

Luis

**Comment by maximbaz** [comment]
I think that's a good idea on how to follow a mouse, though I personally would rather prefer to follow a screen that has focused window... if there was such API.

**Comment by luisdavim** [comment]
Alfred has both options and I was using "follow active screen" and then switched to "screen containing mouse" and I actually prefer that. 
For me it would be great if you could add this option. 
Thanks.

**Comment by maximbaz** [comment]
I think long-term we should target having both options as well, and for now since we know how to implement "follow the mouse" it should be added right away :+1:

**Comment by luisdavim** [comment]
Awesome, thanks.

**Comment by KELiON** [comment]
@luisdavim I couldn't find these options in Alfred. Is it somewhere in settings?

**Comment by luisdavim** [comment]
@KELiON it's under the appearance tab on the theme options (button on the bottom left).
<img width="521" alt="screen shot 2017-02-23 at 2 43 30 pm" src="https://cloud.githubusercontent.com/assets/173006/23263577/8c1358e0-f9d6-11e6-9a2a-f1b77c2ba034.png">

**Comment by KELiON** [comment]
@luisdavim now I see, thanks. I have only one concern: how can it work together with "save position" option? I.e. case:

1) Check "save position" checkbox;
2) Move window somewhere on screen 1 and hide the window;
3) Move cursor to screen 2 and use shortcut to show window;
4) Where the window should appear? 

I'd try to find some universal solution. I don't like too much configuration options and I think that the more configuration options users have, the less they use.

**Comment by luisdavim** [comment]
with one of these options enabled, follow mouse or active window the position that is saved is relative to the monitor instead of absolute across all monitors.

**Comment by Kageetai** [comment]
Hmm maybe do it similar to Alfred and have an exclusive option to either follow mouse or save position?!

**Comment by luisdavim** [comment]
I would say, with follow mouse enabled, you save the position relative to the screen, if not, you save the absolute position. That way you only need a toggle to follow mouse or not and the default behaviour is kept. 
What do you think?

**Comment by maximbaz** [comment]
There's no need to have exclusive mode, now we detect a primary screen and save position based on its ID, if the "follow cursor" mode is enabled, we could just use exactly the same algorithm but base it on the "detected screen". That way, you could choose favorite positions on each of your screens, and they all will be remembered.

**Comment by maximbaz** [comment]
To give you some context, [this](https://github.com/KELiON/cerebro/blob/71d5bb1e80e690579dd1724d11e2108424ccb90f/app/main/createWindow.js#L60-L63) is the logic of storing the window position after it was moved. As you can see, the primary screen is detected, and its ID is used to save the position in the config. Supply it with "active" display instead, and the position will be stored for that screen instead.

[Here](https://github.com/KELiON/cerebro/blob/71d5bb1e80e690579dd1724d11e2108424ccb90f/app/lib/getWindowPosition.js#L31) is how the window position is restored, again it is based on the primary screen, replace it with "active" to load the proper position.

**Comment by luisdavim** [comment]
That sounds like an awesome idea!
