### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by prcastro** [cerebroapp/cerebro#134]
Would be nice to have a Flatpak package for cerebro, so we can install easily on every Linux distro

**Comment by maximbaz** [comment]
Electron-builder doesn't support Flatpack yet - vote for it here: https://github.com/electron-userland/electron-builder/issues/512

You may also be interested to share your opinion in #117.

**Comment by KELiON** [comment]
omg, one more Linux package format 😱. 

@prcastro we are planning to add support for `snap` packages. Why would you prefer Flatpak over snap?

**Comment by prcastro** [comment]
Snap is a centralized approach by Canonical. Flatpak is made by RedHat, with a more distributed apporoach. The number of contributors of Flatpak is higher than Snap or AppImage, and it's being used by GNOME (on distros like Fedora, RedHat, Arch and others) and it's been considered by KDE and ElementaryOS as the next default packaging format. Skype, Telegram, Spotify, Libreoffice, Blender and GNOME apps all have flatpaks available.

Also, the security approach used by Flatpak seems much better than snap. It works by using portals to communicate to the exterior world. Also, flatpak apps are much smaller, since they can share a runtime (a bunch of common libs, that are independent from the apps, like OpenSSL).

**Comment by dar5hak** [comment]
Agree with @prcastro, except that Canonical no longer controls the roadmap of snap. They handed it over to a committee which has people from elementary, Fedora, KDE, etc.

Not saying it's the better format, just mentioning a recent change. :slightly_smiling_face:

**Comment by oguhpereira** [comment]
We are not building for flatpack at the moment.
