### ISSUE TITLE
Proxy settings

### ISSUE THREAD

**Issue by prcastro** [cerebroapp/cerebro#135]
There is no proxy settings on the settings screen

**Comment by rcalsaverini** [comment]
Expanding on what @prcastro said, I'm having problems installing plugins behind a corporate proxy. The queries work, but the plugins don't.

**Comment by exislow** [comment]
I have exact the same problem as @rcalsaverini 

Can someone fix this?

**Comment by jiffyrune** [comment]
use proxychain?

**Comment by letroll** [comment]
there are something like proxychain for windows and free?

**Comment by baddym** [comment]
having the same issue. Cannot use cerebro behing a corporate proxy
Will there be a fix anytime soon?

**Comment by letroll** [comment]
@baddym I have switched to http://keypirinha.com for now

**Comment by skyf0cker** [comment]
So is there a good solution to set a proxy for google search or stackOverflow today?
