### ISSUE TITLE
URLs are opening with Firefox instead of Chrome

### ISSUE THREAD

**Issue by naps62** [cerebroapp/cerebro#173]
Running on Arch Linux with i3 here.

Google chrome is opened right next to Cerebro, and running `xdg-open http://google.com` on a terminal  opens a new tab on chrome.

But cerebro is somehow opening urls on Firefox instead. I guess this is probably not a bug in cerebro, but in my OS configs. But how is cerebro figuring out what the default browser is, so I can properly configure my machine?

**Comment by maximbaz** [comment]
In the end [shell.openExternal](https://github.com/electron/electron/blob/master/docs/api/shell.md#shellopenexternalurl-options-callback) is used, you might want to continue investigating on Electron's side. 

You are right, it's probably something with your OS configs, I'm also on Arch with i3, have both Chrome and Firefox, and both Cerebro and `xdg-open` open Chrome.

**Comment by helionmelion** [comment]
I didnt figure out how to resolve this, I have this issue here too
