### ISSUE TITLE
(Feature/Plugin Request) iTunes Integration

### ISSUE THREAD

**Issue by TheBusyBiscuit** [cerebroapp/cerebro#175]
I would love to be able to search and play songs from my iTunes Library using Cerebro.
I am sure this would rather be a Plugin instead of an integrated feature but I may post it here nonetheless.

Side note: I am using Windows 10, so it would be lovely if this was not a Mac-Only feature.

**Comment by KELiON** [comment]
@TheBusyBiscuit question: how do you see this plugin, only search and start playing of the song from your library? Do you need controls like next/prev/pause?

**Comment by TheBusyBiscuit** [comment]
well as many as controls as possible would be perfect but only if that is possible, I don't really know how far iTunes' API goes when it comes to JavaScript. But I am mainly looking for queries like
'iTunes Smash Mouth' (artist)
or
'iTunes All Star' (song name)
to show songs and then be able to play them via click.

But I don't really think the next/prev controls would make too much sense in searching songs.

**Comment by oguhpereira** [comment]
@TheBusyBiscuit the suggestion is very good, we are centralizing [here](https://github.com/cerebroapp/cerebro/issues/112). Could you add it over there?
