### ISSUE TITLE
Entering the € character on certain keyboards causes the input field to be overwritten

### ISSUE THREAD

**Issue by SquirrelsMcGee** [cerebroapp/cerebro#201]
On a Lenovo Thinkpad x230 using UK layout, you have to press `Alt Gr + 4` in order to type €

Expected result: € character added to end of input
Actual result: Input overwritten, only € remains

Update: In some cases it works as expected, for example writing `€50` works fine, and subsequently `€50€`, however writing `50€` does not

**Comment by KELiON** [comment]
@SquirrelsMcGee Wow, interesting. Do you know how `AltGr` works? Is it just another functional key or it is equivalent of `alt+(other key, like ctrl/shift)`?

**Comment by SquirrelsMcGee** [comment]
No i don't unfortunately, but I do believe it's a modifer key and that it appears on many UK style keyboards

**Comment by maximbaz** [comment]
<kbd>AltGr</kbd> is a separate modifier key, Windows identifies <kbd>AltGr</kbd> as <kbd>Ctrl+Alt</kbd>, but it's not common on other OS. For example on my Linux I have no problems typing `€` sign using <kbd>AltGr</kbd>, but if I type <kbd>Ctrl+Alt+any_number</kbd>, that indeed clears the line.

So it needs to be investigated, why <kbd>Ctrl+Alt+number</kbd> clears the input.

**Comment by dubisdev** [comment]
The error comes from https://github.com/cerebroapp/cerebro/blob/606a1ba6f83f6268510001f98fc864e5816b67b2/app/main/components/Cerebro/index.js#L213 where the function is being called without passing event as the second parameter.

If we want cerebro to select a result on `ctrl+number` we need to:
- Avoid entering the if condition when `alt` is pressed (to avoid selecting when using `ctrl+alt`)
- Pass the event to the function as second parameter
https://github.com/cerebroapp/cerebro/blob/606a1ba6f83f6268510001f98fc864e5816b67b2/app/main/components/Cerebro/index.js#L289

And might be cool to document this behaviour so the users know this shortcut is available
