### ISSUE TITLE
Unable to find new apps installed on macOS

### ISSUE THREAD

**Issue by KTachibanaM** [cerebroapp/cerebro#211]
After a new app is installed under `/Applications` on macOS Sierra, I was not able to find the new app installed until restarting cerebro.

**Comment by matmunn** [comment]
I had this problem as well

**Comment by KTachibanaM** [comment]
Looks like it only happens with apps installed with App Store (a .dmg install doesn't have this problem)

**Comment by matmunn** [comment]
I had the problem when installing from a .dmg

**Comment by KELiON** [comment]
@matmunn I'll try to reproduce it. Looks like [this watcher](https://github.com/KELiON/cerebro/blob/master/app/main/plugins/core/osx-apps/index.js#L92) is not always triggered
