### ISSUE TITLE
How to install plugins manually? – add information to Readme.md

### ISSUE THREAD

**Issue by mubaris** [cerebroapp/cerebro#220]
I am not able to install plugins using `plugins` keyword. I guess it's a network proxy problem or something else. Can anyone please explain how to do it manually?

**Comment by antimercy** [comment]
me too facing the same issue.

**Comment by KELiON** [comment]
@mubaris @antimercy you can install them using `npm` – open in terminal [config file path](https://github.com/KELiON/cerebro#config-file-path), go to folder `cd ./plugins` and run `npm install --save name-of-plugin`

**Comment by mubaris** [comment]
Thank you @KELiON

**Comment by vicary** [comment]
This should really be written in README.md.

**Comment by sarthak96** [comment]
^ +1. manual installation should be in readme.md

**Comment by KELiON** [comment]
I'm reopening this one till we add it to Readme

**Comment by fabiovanderlei** [comment]
Thank you!

**Comment by thedonquixotic** [comment]
I have also run into this problem. If installing manually is the only way to install then that information should also be added to the readme. As of now plugin manager is still listed as a feature for the app but as far as I can tell it doesn't work?

**Comment by oguhpereira** [comment]
we are having some problems with the project, but looking for solutions. The installation of the manual pluggin will also be corrected

I created a pr to add the information in the readme

Thank you guys
