### ISSUE TITLE
[Feature request] Google translate API

### ISSUE THREAD

**Issue by AlexSHoffman** [cerebroapp/cerebro#225]
Are there any ways to implement google translate API in cerebro, without breaking their API terms and conditions?

Google translate now can translate several more languages using its new neural network translate system, which is a lot better than older google translate algorithms which are already better than Yandex.Translate. I'm, personally just go to translate.google.com in like 8/10 cases, after receiving some nonsense translate from Yandex plugin, when translating some complicated words/sentences.

What do you guys think?

**Comment by KELiON** [comment]
@AlexAlabyev can you check if they have any free api? When I was trying to find it, they didn't have any free translate API so I decided to include yandex API instead

**Comment by AlexAlabyev** [comment]
@KELiON it seems like they don't have free API, but, maybe one of these could work with cerebro?:
- [https://github.com/matheuss/google-translate-api](https://github.com/matheuss/google-translate-api) 
- [https://ctrlq.org/code/19909-google-translate-api](https://ctrlq.org/code/19909-google-translate-api)

**Comment by KELiON** [comment]
@AlexAlabyev first one looks good! I'll check it out

**Comment by oguhpereira** [comment]
@AlexSHoffman thanks for the suggestion, today we have a system that allows you to add external plugins. This would be a great plugin. But I don't think it would be interesting to attach to the core.
