### ISSUE TITLE
Baloo support [Feature request]

### ISSUE THREAD

**Issue by eemantsal** [cerebroapp/cerebro#236]
Could Baloo (the desktop search indexer for the Plasma desktop) be supported in Cerebro? This way the KDE5/Plasma users could do document, file, web bookmarks, etc, search by content or tags, which is a very useful feature.

Thanks for you neat app.

**Comment by dubisdev** [comment]
Hi @eemantsal 

Baloo support can be enabled if someone creates a plugin for that. We are moving this to the plugin requests thread.

moved to #112
