### ISSUE TITLE
Option to specify port

### ISSUE THREAD

**Issue by DrNightmare** [cerebroapp/cerebro#242]
Currently, `yarn run dev` runs the app on port 3000 on localhost. It seems the port is hard coded in server.js. 
It would be helpful if we could specify the port as a command line argument to the yarn run command, seeing as 3000 is a very common port which is used as default by several applications.

**Comment by KELiON** [comment]
@DrNightmare makes sense! Can you do a pr? I think should be small change

**Comment by oguhpereira** [comment]
Thanks for the suggestion, I opened a pr to solve this
