### ISSUE TITLE
Plugin idea: search in browser bookmarks

### ISSUE THREAD

**Issue by FIJN** [cerebroapp/cerebro#297]
Hello! Idea:
Add search in browser bookmarks.

**Comment by KELiON** [comment]
@FIJN hey! What browser do you use?

I think as first version it could be one browser oriented plugin, but would be great to create one browser for all popular browsers (chrome, firefox, safari, opera, IE), that can retrive from system default browser and show only these bookmarks (or browser can be configurable)

**Comment by FIJN** [comment]
Lets start Google Chrome browser.

**Comment by adrian011494** [comment]
I am working in this idea.. :)

**Comment by tokozedg** [comment]
+1 for Firefox

**Comment by brpaz** [comment]
Here it is: https://github.com/brpaz/cerebro-chrome-bookmarks

@KELiON when can we expect the release with the fix for plugin settings?

**Comment by KELiON** [comment]
@brpaz nice plugin! I'll try to release it on this week

**Comment by oguhpereira** [comment]
@FIJN thanks for this issue

we are trying to centralize plugin requests over here #112 

I think it was not possible to go ahead with this idea at the moment, so I am closing
