### ISSUE TITLE
open search results doesn't work

### ISSUE THREAD

**Issue by bobblkabb** [cerebroapp/cerebro#320]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: deepin 15.4
- **Cerebro.app version**: 0.28
- **Relevant information from devtools** _(See above how to open it)_:  N/A

## Issue
Can't open search results in firefox. It's the only browser on the system and set as 'default' in the system settings. Nothing happens when I click a search result.
No difference between ddg and google.

**Comment by bobblkabb** [comment]
update: works with .deb package

**Comment by KELiON** [comment]
@bobblkabb did you install it from releases page on github?

**Comment by bobblkabb** [comment]
@KELiON No, from the cerebro website

**Comment by dubisdev** [comment]
I'm closing this issue as outdated. Cerebro is currently in [`v0.9.0`](https://github.com/cerebroapp/cerebro/releases/tag/v0.9.0).
Give it a try and, if the error persists, feel free to open a new issue.
