### ISSUE TITLE
result preview

### ISSUE THREAD

**Issue by JiangWeixian** [cerebroapp/cerebro#344]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Cerebro.app version**: 
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

![cerebro](https://user-images.githubusercontent.com/6839576/27007708-fede3838-4e8e-11e7-8e19-bfb80721b938.png)

in v.0.2.8, i don't have this problem.
but in v.0.3.0.alpha & alpha2 i meet this problem

**Comment by maximbaz** [comment]
Related: #285
