### ISSUE TITLE
no desktop entry on ubuntu

### ISSUE THREAD

**Issue by jkanche** [cerebroapp/cerebro#352]
Hi,

If i run cerebro for the first time using the terminal, I see the following errors in the terminal

> /usr/local/share/applications/appimagekit-cerebro.desktop: error: value "public.app-category.productivity;" for key "Categories" in group "Desktop Entry" contains an unregistered value "public.app-category.productivity"; values extending the format should start with "X-"
> Error on file "/tmp/.mount_dPBpl3/cerebro.desktop": Failed to validate the created desktop file

How do i fix this ?

EDIT - 
this doesn't happen if i use the .deb release package.

**Comment by KELiON** [comment]
@jkanche does it work after this error?

**Comment by jkanche** [comment]
it does, but cerebro won't start automatically on startup and there's no desktop shortcut because of teh error. I'd have to run the appimage everytime I restart my computer..

**Comment by Dev-Owl** [comment]
Hi,
Can confirm the same on XUbuntu (Ubuntu 16.04.2 LTS)

```
error: value "public.app-category.productivity;" for key "Categories" in group "Desktop Entry" contains an unregistered value "public.app-category.productivity"; values extending the format should start with "X-"
Error on file "/tmp/.mount_ArJNzi/cerebro.desktop": Failed to validate the created desktop file

```
The application is working after this issue but is not installed or added to the menu/desktop.

**Comment by MrSherish** [comment]
I've run into the same issue on fresh install of Fedora 26:
`/home/w1cked/.local/share/applications/appimagekit-cerebro.desktop: error: value "public.app-category.productivity;" for key "Categories" in group "Desktop Entry" contains an unregistered value "public.app-category.productivity"; values extending the format should start with "X-"
Error on file "/tmp/.mount_czU9Ob/cerebro.desktop": Failed to validate the created desktop file`

**Comment by oguhpereira** [comment]
The old version had several compilation problems. I believe it has now been resolved

cc @MrSherish @jkanche @Dev-Owl @danielbushman
