### ISSUE TITLE
Error starting application

### ISSUE THREAD

**Issue by lestevam** [cerebroapp/cerebro#354]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu Gnome 16.04 
- **Cerebro.app version**: 0.3.0 

## Issue
I tried to install by appimage but there is an error with the desktop file.
Then I performed the installation with the .deb package and the installation problem did not occur, but when I run the app it triggers the following error.

Uncaught Exception:
Error: EACCES: permission denied, open '/home/myuser/.config/Cerebro/config.json'
     At Object.fs.openSync (fs.js: 558: 18)
     (Anonymous function) [as openSync] (ELECTRON_ASAR.js: 173: 20)
     At Object.fs.writeFileSync (fs.js: 1233: 33)
     At Object.get (/opt/Cerebro/resources/app.asar/main.js:157:18)
     At module.exports.exports.default (/opt/Cerebro/resources/app.asar/main.js:1546:38)
     At module.exports.exports.default (/opt/Cerebro/resources/app.asar/main.js:692:50)
     At App.module.exports._electron.app.on (/opt/Cerebro/resources/app.asar/main.js:1663:43)
     At emitTwo (events.js: 111: 20)
     At App.emit (events.js: 191: 7)

**Comment by KELiON** [comment]
Hey, @lestevam! Can you answer two questions?
Do you have several users on your computer? Do you install and use application using the same user?

**Comment by lestevam** [comment]
Hey, @KELiON!

On the computer I´m testing, I have only one user.
I tried install without sudo, but this is not work, so I installed with root user.

**Comment by benjaminjacobreji** [comment]
Hi, @KELiON 
I too have this problem..please advise how to solve this please..
Im on ubuntu 17.04 and am using cerebro_0.3.0_amd64.deb package

**Comment by oguhpereira** [comment]
@lestevam Were you able to solve the problem? I will close understanding that it was solved

https://github.com/cerebroapp/cerebro/issues/354#issuecomment-315565121

**Comment by lestevam** [comment]
Hi @oguhpereira for me you can close, I'm not using Linux at the moment and  I don't remember if I was able to solve this problem at that time.
