### ISSUE TITLE
Hotkey to open DevTools

### ISSUE THREAD

**Issue by maximbaz** [cerebroapp/cerebro#358]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: ArchLinux
- **Cerebro.app version**: 0.3.0
- **Relevant information from devtools** _(See above how to open it)_: N/A

## Issue

I usually hide tray icon, and when I need DevTools it's very annoying as I have to enable tray icon, use it to open DevTools and disable tray icon again.

The [plugins/boilerplate.md](https://github.com/KELiON/cerebro/blob/master/docs/plugins/boilerplate.md)  says `Use cmd+alt+i to open developer tools in Cerebro`, however this does nothing (on Linux?) and I didn't find any reference in the code which might be implementing this.

Let's create a shortcut 🙏

**Comment by KELiON** [comment]
I like the idea! Actually, I don't remember why I removed this shortcut, but should be ok to have this shortcut (we can copy from [boilerplace](https://github.com/chentsulin/electron-react-boilerplate/blob/585b4f4d30d4e6e94b5e31a11e56487dac66d022/app/menu.js#L78)), but only when developer mode is turned on
