### ISSUE TITLE
Typing/clearing text changes the size and position of the search bar

### ISSUE THREAD

**Issue by serin113** [cerebroapp/cerebro#365]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 64-bit
- **Cerebro.app version**: 0.3.0
- **Relevant information from devtools** _(See above how to open it)_: N/A

## Issue
Typing on the search bar and clearing it both increments the bar's width *and* shifts its position up by a few pixels.
http://i.imgur.com/BMkhjkD.gifv

Not quite sure what the cause is, since this hasn't happened on my Arch installation.

The display is set at a custom scaling size of 120, in case that matters. http://i.imgur.com/cxqlUfg.png

**Comment by dubisdev** [comment]
I'm closing this issue as outdated. I seems to be resolved in [`v0.9.0`](https://github.com/cerebroapp/cerebro/releases/tag/v0.9.0)

Give it a try and, if the problem persists, feel free to open a new issue.
