### ISSUE TITLE
Initialize not triggering

### ISSUE THREAD

**Issue by Wolvan** [cerebroapp/cerebro#390]
I am using the following code right now
```js
'use strict';

function init() {
    console.log("Done");
}

function main({ term, display }) {
    display({
        title: `You've entered ${term}`
    });
}

module.exports = {
    initialize: init,
    fn: main
};
```

`Done` never ends up being logged in the console for some reason and even trying to use breakpoints seems to fail completely, as initialize is never called for me.

**Comment by KELiON** [comment]
@Wolvan It looks super weird for me, but I could reproduce it and it start to work for me when I add an empty `initializeAsync` function. So if you add `initializeAsync: () => {},` to your `module.exports` it works

**Comment by oguhpereira** [comment]
Because it is a very old doubt, I think it may no longer exist. If it still remains, I will reopen the case
