### ISSUE TITLE
[Feature/Plugin Request] JavaDocs integration

### ISSUE THREAD

**Issue by Tim3game-zz** [cerebroapp/cerebro#394]
As the title says, the possibility to add javadocs documentations from only a URL/Search term. Som you would time something like:

**jdocs Spigot** - and it would bring out every docs find to the term **Spigot**
**jdosc https://hub.spigotmc.org/javadocs/spigot/** - It would find, download, and save the docs
**jdocs spigot getInventory()** - It would bring out all finds, and you could select, and in a short view, there would be come sort text to the find, and on clicking a button it would open the webpage for it

**Comment by alexweber** [comment]
There's already pretty great offline doc viewers for every major platform, it's probably be saner to integrate with them as opposed to re-inventing the wheel here....

**Comment by KELiON** [comment]
Looks like you can integrate docs only for third-party java libraries, since core javadocs are [restricted to distribute](http://docs.oracle.com/javase/7/docs/legal/cpyr.html):

> This software and related documentation are provided under a license agreement containing restrictions on use and disclosure and are protected by intellectual property laws. Except as expressly permitted in your license agreement or allowed by law, you may not use, copy, reproduce, translate, broadcast, modify, license, transmit, distribute, exhibit, perform, publish, or display any part, in any form, or by any means.

**Comment by oguhpereira** [comment]
Very good!

you can add the idea in this issue, at the moment we will try to solve some problems, but then we will create some plugins
