### ISSUE TITLE
It's possible to make plugin from shell script ?

### ISSUE THREAD

**Issue by PrzemekSkw** [cerebroapp/cerebro#400]
Hi, I have that script to find text in xls files: [https://pastebin.com/vC50y8Nn](url)
Is it possible to make plugin to cerbero with that script?

**Comment by Pectojin** [comment]
You should take a look at https://github.com/KELiON/cerebro-shell

That particular plugin allows you to call any shell command, so it should be fairly straight forward to rewrite that plugin to call a full script and perhaps take an input to put into the script.

**Comment by oguhpereira** [comment]
@PrzemekSkw try to use the [cerebro-shell](https://github.com/KELiON/cerebro-shell) it is very good
