### ISSUE TITLE
In app version number differ from installer/installed executable

### ISSUE THREAD

**Issue by duianto** [cerebroapp/cerebro#403]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Microsoft Windows 10 Version 1607 (OS Build 14393.1770)
- **Cerebro.app version**: 0.3.0 or 0.3.1 
- **Relevant information from devtools** N/A

## Issue

The version number in Cerebro doesn't match the version number of the installer or the installed executable.

Opening Cerebro and typing `version` shows `Cerebro Version` as an option, selecting it, shows: `0.3.0`
in the right panel.

![cerebro_2017-11-07_08-59-31](https://user-images.githubusercontent.com/13420573/32482915-12c1d42e-c39a-11e7-9a8e-0dcac5fa03a1.png)

But the installer is called: `cerebro-setup-0.3.1.exe`
And in the windows file explorer, the properties, details tab for both the installer and the installed Cerebro executable: `C:\Program Files\Cerebro\Cerebro.exe`, show: `File version: 0.3.1.0`.

![dllhost_2017-11-07_09-00-50](https://user-images.githubusercontent.com/13420573/32482982-592cb9ba-c39a-11e7-807e-627a5c771eeb.png)
![dllhost_2017-11-07_09-01-16](https://user-images.githubusercontent.com/13420573/32482983-59606968-c39a-11e7-945e-a128e815d8ba.png)

**Comment by Stanzilla** [comment]
Can confirm

**Comment by dubisdev** [comment]
This might be relate to not updating the pakcage.json versions in both `package.json` and `app/package.json`.

I'm closing this as we have:
- Moved to app.getVersion() -> #585 
- Updated the documentation to avoid this errors
