### ISSUE TITLE
Looking for maintainer for rpm package for Fedora/RHEL

### ISSUE THREAD

**Issue by johnnyasantoss** [cerebroapp/cerebro#406]
It exists or plans for making it?
Thanks!

**Comment by KELiON** [comment]
@maximbaz as our linux guru, do you know something about it?:)

**Comment by maximbaz** [comment]
I'm not familiar with Fedora myself, but I've seen similar request in a different Electron app, and I'll quote their reasoning to not support rpm package out of the box:

> We are currently not planing to build rpm releases. One reason is that updates can only be assured with a repository and we currently do not want to maintain two different repos. Having said that we are always happy to work closely together with a fedora package maintainer if someone wants to pick it up: https://fedoraproject.org/wiki/Package_maintainer_responsibilities

To me it sounds like a reasonable approach, just like I'm maintaining AUR package for ArchLinux, it's best to find some actual user of Fedora who will create and maintain a rpm package for this OS. This way you also ensure that with every new version there is at least one person (package maintainer) who successfully upgraded to a new version and tested that it works on Fedora 🙂

**Comment by johnnyasantoss** [comment]
oh :(
I could help but I'm not having much free time lately. That's why I was asking for it.
Alternatively we could have a bash script to download the `appimage` file, make it executable in a `/opt/` folder and set it up to start on user login 🤔 
Is this possible? It would reduce the installation friction

**Comment by johnnyasantoss** [comment]
anyway, thanks for your quick reply 😃

**Comment by maximbaz** [comment]
Since creating such script is a rather specific and temporary workaround, you probably should just create your own local script for this 🙂 

Having someone maintaining rpm package is a long term solution, let's see if you or someone else get time and desire to work on it in the future 🙂

Maybe rename the issue to something like this, to bring attention?

`Looking for maintainer for rpm package for Fedora/RHEL`

**Comment by johnnyasantoss** [comment]
Yep, I'll edit the title then and hope for someone to make this possible

**Comment by rcelha** [comment]
What about supporting flatpak or snap? Fedora supports flatpak, right?

**Comment by johnnyasantoss** [comment]
Right!
Flatpak is an interesting proposal. There's many more distros that support flatpak out of the box and in Fedora it integrates pretty well with Gnome and the desktop environment.

**Comment by oguhpereira** [comment]
So far, we have not evolved any support for these commented points.

For now, let's stick with the build available for electron.
