### ISSUE TITLE
Make Cerebro available as a desktop app

### ISSUE THREAD

**Issue by PurpleBabar** [cerebroapp/cerebro#418]
Hi :)

Cerebro is a great app, but i wanted to be able to lauch it from plank ubuntu, there fore i needed a .desktop file, so i made one and a gist in case it could help someone else :)

https://gist.github.com/PurpleBabar/b7ab56435a172b743a8f5f3b255c4cb3

Hop it can helps someone else :)

**Comment by brpaz** [comment]
If I remember well, when I installed Cerebro, it created the Desktop file automatically. How did you install Cerebro? Deb or AppImage?

**Comment by PurpleBabar** [comment]
AppImage :) I just madethe gist for people that used the appImage and wanted itavailable on desktop ;)

**Comment by brpaz** [comment]
OK. I think deb created by default the .desktop

**Comment by oguhpereira** [comment]
@PurpleBabar very happy for that explanation

thanks for the gist
