### ISSUE TITLE
Unable to compile on node v9, which blocks upgrading on Arch Linux

### ISSUE THREAD

**Issue by maximbaz** [cerebroapp/cerebro#426]
Arch Linux
yarn: 1.3.2
node: 9.2.0

---------------

Please follow **exactly** these steps (don't use repo that you had cloned before):

```
$ git clone https://github.com/KELiON/cerebro.git cerebro
$ cd cerebro
$ yarn
.....
$ cd app
$ yarn
```

Expected: both `yarn` runs succeed.
Actual: the second `yarn` fails.

```
❯ yarn
yarn install v1.3.2
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.1.1: The platform "linux" is incompatible with this module.
info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠄ ref:    ^~~~~~~~~~
[-/2] ⠄ waiting...
[-/2] ⠄ waiting...
[-/2] ⠄ waiting...
error /home/maximbaz/private/cerebro/app/node_modules/ref: Command failed.
Exit code: 1
..........
..........
..........
make: *** [binding.target.mk:95: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/maximbaz/private/cerebro/app/node_modules/ref/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:159:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:12)
gyp ERR! System Linux 4.13.12-1-ARCH
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/maximbaz/private/cerebro/app/node_modules/ref
```

**Comment by KELiON** [comment]
Can you double check that latest master doesn't work? I did [small fix](https://github.com/KELiON/cerebro/commit/b379a5b90ba63df99155210ef043d69ae785e6a6), maybe it is related. BTW, when I did a release everything was ok for me (using MacOS for that)

**Comment by maximbaz** [comment]
Just checked, exactly the same issue when cloning the repo from scratch. I'm hesitant to update AUR to 0.3.2 because everyone will start complaining because of this 🙂

**Comment by KELiON** [comment]
@maximbaz what version of node do you use? I could reproduce this issue on node 9.0.0, but everything is ok with v7.10.1. I

**Comment by maximbaz** [comment]
I have `v9.2.0`, Arch Linux ships the latest available version of all apps, so every Arch Linux user has node `v9.2.0` and it's not something I can change... Let's fix Cerebro for node `v9` 🙂

**Comment by HoroKun** [comment]
Any news? I would really like to get the new update but to get it not from the AUR is not the way I like ^^

**Comment by michaelwapp** [comment]
I can confirm that it doesn't build with arch and node 9, please update :+1:

**Comment by FliiFe** [comment]
Any update ? #451 has a fix, why not implement it on the main repo ?

**Comment by mayankDhiman** [comment]
Any updates? It doesn't work with gnome & node 9. Also is there a simple workaround?

**Comment by AlanTheKnight** [comment]
Hey, any updates?
