### ISSUE TITLE
Could not make .deb work on Ubuntu 16.04 

### ISSUE THREAD

**Issue by patilswapnilv** [cerebroapp/cerebro#444]
Hi @KELiON 
Thanks for building this! It's beautiful. 

I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) using Ubuntu 16.04; I downloaded the cerebro_0.3.2_amd64.deb from the releases on Github since the once on the website for Linux seems to be an AppImage (I don't know how that works with Ubuntu :-( )

- **OS version and name**: Ubuntu LTS 16.04
- **Cerebro.app version**: 0.3.2
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue
I see a JavaScript error whenever I try to launch the app. I do not search anything, (It does not even let me type anything). Sometimes when I use Ctrl+Space, it search bar does comeup, I can type in as well, but it does nothing. 
what the
![screenshot from 2018-01-18 17-25-56](https://user-images.githubusercontent.com/1833516/35097609-da1ddf3a-fc76-11e7-8d72-cd35df3f10bb.png)

Please suggest if there is something I can do to fix this.

Regards, 
Swapnil Patil

**Comment by iTemkSav** [comment]
Had the same issue on Ubuntu 16.04.
I build from source code and it worked for me

**Comment by JulienAllard** [comment]
Same issue here with a fesh install of Mint 18.3. I installed the package _cerebro_0.3.2_amd64.deb_. When I launch it I get these two errors. Then if I press Ctrl+Space I get an input box but it does not make any action then.
![cerebro](https://user-images.githubusercontent.com/36508687/36261744-63c5aec6-1233-11e8-93ce-b8613daffd40.png)
![cerebro1](https://user-images.githubusercontent.com/36508687/36261745-63d392c0-1233-11e8-83a4-02782ac48722.png)

**Comment by iraklisg** [comment]
Same issue here on a fresh Mint 18.3 (cinnamon) install

**Comment by eleveni386** [comment]
Same issue on my Deepin 15.5 I installed AppImage

**Comment by ToxaZ** [comment]
Same issue on Ubuntu 17.10  I installed the package cerebro_0.3.2_amd64.deb

**Comment by Strum355** [comment]
same here, ubunut 17.10, node 9.11.1

**Comment by andystevens91** [comment]
Same error happens to me with Ubuntu 17.10, with both the .deb and the .AppImage versions.

**Comment by Strum355** [comment]
the AppImage works for me, .deb doesnt

**Comment by hqweay** [comment]
same here, deepin 15.5.

**Comment by xmr-red** [comment]
Same issue on Elementary Loki

**Comment by dubisdev** [comment]
This error is related to the tracking functionality that has been removed. I'm closing this as outdated.
