### ISSUE TITLE
Close Cerebro upon using 'CTRL+C'

### ISSUE THREAD

**Issue by FlorisWarmenhoven** [cerebroapp/cerebro#447]
OS: Windows 10 Pro build 16299
Cerebro version: 0.3.1 (0.3.2 crashes on launch, you're already aware of it)

I don't know whether this is a feature request or a bug, but when I copy a value from the Cerebro text box bar - I would like Cerebro to close. In _all_ of my usecases, when I copy a value - I'm done with Cerebro.

I checked all the other issues, I couldn't find something similar to this. 

Love this app, keep up the great work!

**Comment by lawgsy** [comment]
Sounds like a decent feature request to me.
