### ISSUE TITLE
Problems developing on Windows

### ISSUE THREAD

**Issue by reflog** [cerebroapp/cerebro#45]
Hi!
First of all - congrats on an awesome project!
I wanted to contribute a plugin to support results from Everthing by voidtools (a great file indexer on Windows) and wrote a plugin https://github.com/reflog/cerebro-plugin-everything
But I cannot test it well, since the instructions are very Mac oriented and don't work in Windows land.
Opening dev tools doesn't work, since they are shown like this:
![image](https://cloud.githubusercontent.com/assets/109876/22377373/4f938844-e4ba-11e6-8499-33a58a6a1b51.png)
And there is no way (that I could find) to see console output from my plugin.

What's your recommended way of debugging on Windows?
Also - how can I mark my plugin as 'windows only' so that other platform users would avoid it?

**Comment by Kageetai** [comment]
Hey, to open dev tools properly, open the menu on the upper left and pop them out as a separate window.

**Comment by reflog** [comment]
Tried that, unable to click any menu :(

**Comment by Kageetai** [comment]
Oh sorry I meant the upper-right and the men with the three dots there

**Comment by reflog** [comment]
I know, but on Windows, this button (...) is non-clickable.

**Comment by KELiON** [comment]
@reflog yep, looks like it is a bug. To open dev-tools you can try to type something (to see some results in cerebro window), and open dev tools after that. In this window is bigger and you can resize it, so you can see dev tools (and try to detach dev tools windows from cerebro windows by clicking ... button).

Also, would be cool to fix it for other users.  [There is](https://github.com/electron/electron/blob/master/docs/api/web-contents.md#contentsopendevtoolsoptions) an option for `openDevTools` in Cerebro and we should always open it in detached window: `openDevTools('detach')`. There are only two calls for that function: [one](https://github.com/KELiON/cerebro/blob/master/app/main/createWindow/AppTray.js#L65) and [two](https://github.com/KELiON/cerebro/blob/master/app/main/createWindow/AppTray.js#L68). Would be awesome if you or someone else can fix it in PR

**Comment by reflog** [comment]
@KELiON - thanks, that worked! Managed to undock the devtools and now able to see the problems.

To communicate with Everything, my plugin is using node-ffi, which is compiled natively and has problems starting under Electron. Here's the log:
```
Plugin: cerebro-plugin-everything
Path: C:\Users\reflog\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-plugin-everything...
Error loading
Error: Could not locate the bindings file. Tried:
 → d:\dev\cerebro-plugin-everything\build\binding.node
 → d:\dev\cerebro-plugin-everything\build\Debug\binding.node
 → d:\dev\cerebro-plugin-everything\build\Release\binding.node
 → d:\dev\cerebro-plugin-everything\out\Debug\binding.node
 → d:\dev\cerebro-plugin-everything\Debug\binding.node
 → d:\dev\cerebro-plugin-everything\out\Release\binding.node
 → d:\dev\cerebro-plugin-everything\Release\binding.node
 → d:\dev\cerebro-plugin-everything\build\default\binding.node
 → d:\dev\cerebro-plugin-everything\compiled\6.5.0\win32\x64\binding.node
    at r (d:\dev\cerebro-plugin-everything\dist\index.js:1:16695)
    at Object.<anonymous> (d:\dev\cerebro-plugin-everything\dist\index.js:1:783)
    at r (d:\dev\cerebro-plugin-everything\dist\index.js:1:194)
    at Object.<anonymous> (d:\dev\cerebro-plugin-everything\dist\index.js:1:26444)
    at r (d:\dev\cerebro-plugin-everything\dist\index.js:1:194)
    at Object.<anonymous> (d:\dev\cerebro-plugin-everything\dist\index.js:1:36093)
    at r (d:\dev\cerebro-plugin-everything\dist\index.js:1:194)
    at d:\dev\cerebro-plugin-everything\dist\index.js:1:570
    at Object.<anonymous> (d:\dev\cerebro-plugin-everything\dist\index.js:1:580)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
```

Do you have any tips on how to package my module correctly so it would work under Cerebro? This is my first attempt at Electron plugin, so it's a new territory for me...

Thanks in advance!

**Comment by KELiON** [comment]
@reflog can you check that this package installed and works? You can just run `node` from `d:\dev\cerebro-plugin-everything\` and try to require it.

**Comment by reflog** [comment]
When I run the code with my local node it runs fine, the problem is with
electron's node runtime being different from my local one.

**Comment by KELiON** [comment]
@reflog ok, another question: can you check that your local node/npm version are the same, that current electron version uses? 

Also, you can try to rebuild your native extensions for electron's node/npm by command: 
```
npm rebuild --runtime=electron --target=1.4.12 --disturl=https://atom.io/download/electron --abi=50
```

**Comment by reflog** [comment]
Yea, that's the path I'm on right now, tried doing the node-gyp rebuild, but after it's done the bindings are at:
c:\Users\reflog\AppData\Roaming\Cerebro\plugins\node_modules\cerebro-plugin-everything\node_modules\ffi\build\Release\ffi_bindings.node

And as you can see from the log I posted before, it's not where Electron is looking for them :(
Any ideas?

**Comment by KELiON** [comment]
@reflog hm, no idea. Maybe [this](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md) can help?

**Comment by KELiON** [comment]
@reflog did you have any success with your plugin? Do you need any help?

**Comment by reflog** [comment]
Well, I've tried following all the steps in the guide that you've referenced with no luck, same result, cannot find the bindings.
If someone more experienced than me in the world of electron-win32-bindings would like to take a stab at it - that would be awesome, the repo is there and waiting :)

**Comment by oguhpereira** [comment]
I believe this problem has already been solved with the new version. @dubisdev
