### ISSUE TITLE
Cerebro windows not visible in Win10

### ISSUE THREAD

**Issue by pulinagrawal** [cerebroapp/cerebro#456]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10 Build 17120.rs4_release
- **Cerebro.app version**: >3.0
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

No windows of cerebro are visible in windows 10 Build 17120.rs4_release
I can see them on mouse over in the task bar but otherwise they do not show up.

**Comment by pulinagrawal** [comment]
It may be a multiple screen issue. You may want to explore that or just close this issue.

**Comment by oguhpereira** [comment]
@pulinagrawal try to use a more recent version if the problem persists we validate it here
