### ISSUE TITLE
Can't manage or install plugins

### ISSUE THREAD

**Issue by vasilvestre** [cerebroapp/cerebro#459]
- [X ] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [ X] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Cerebro.app version**:  0.3.1.
- **Relevant information from devtools** _(See above how to open it)_: 
[rpc] emit showTerm
main.bundle.js:1 Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at Object.o (main.bundle.js:1)
    at Object.c (main.bundle.js:1)
    at S.t (main.bundle.js:1)
    at h (main.bundle.js:1)
    at Function.ii (main.bundle.js:1)
    at t (main.bundle.js:1)
    at ei (main.bundle.js:1)
    at main.bundle.js:1
    at m (main.bundle.js:1)
    at Sn (main.bundle.js:1)

## Issue
Whenever I try to manage Plugins using right clic => plugins or write plugins it doesn't work.

**Comment by Trapov** [comment]
I'm experiencing the same issue, and the same error-trace exactly.

**Cerebro version**: 0.3.0

**Comment by N0xFF** [comment]
Try latest version from https://github.com/KELiON/cerebro/releases

**Comment by Dean-Coakley** [comment]
Pretty much a duplicate of: https://github.com/KELiON/cerebro/issues/457

**Comment by vasilvestre** [comment]
I think that the download link at https://cerebroapp.com/ should be updated. .exe download is a link to 0.3.1.

**Comment by zbhoy** [comment]
Is development dead?

**Comment by KELiON** [comment]
@zbhoy I a bit busy during last several months, but I'll try to check and fix all active issues 💪

**Comment by zbhoy** [comment]
@KELiON Totally understand! Glad to see you are back. Been using the app even with the current errors because I haven't found anything better

**Comment by dubisdev** [comment]
I'm closing this as a duplicate of #457 that has been also closed as resolved
