### ISSUE TITLE
Wierd behaviour with developing Electron apps.

### ISSUE THREAD

**Issue by foxt** [cerebroapp/cerebro#462]
- [] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 10
- **Cerebro.app version**: 0.3.0
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

For some reason, it kept locking my "default_app.asar" on my desktop files, blocking me from developing electron apps

![image](https://user-images.githubusercontent.com/12257112/39087097-90391fae-4593-11e8-8174-664964fe9d70.png)

**Comment by KELiON** [comment]
@theLMGN  can you add more details to reproduce this issue?

**Comment by dubisdev** [comment]
I'm closing this as outdated. Try with the new version in `master` and if the problem persists we can open another new.
