### ISSUE TITLE
Cerebro crashes at startup.

### ISSUE THREAD

**Issue by dschuessler** [cerebroapp/cerebro#463]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- macOS 10.13.4 
- Cerebro 0.3.2 
- I don't even get far enough to open dev tools. 

## Issue
I installed the latest Cerebro version with `brew cask install cerebro` and get this error at launch.

![bildschirmfoto 2018-04-28 um 09 22 53](https://user-images.githubusercontent.com/5774545/39393520-7bec6e06-4ac6-11e8-8e3e-cf8765a8419e.png)

**Comment by zgayjjf** [comment]
same here

**Comment by mybluevan** [comment]
Similar problem here when upgrading from 0.3.1 to 0.3.2 on OSX 10.13.4. Seems to be part of #434 though. ![screen shot 2018-05-03 at 02 11 42](https://user-images.githubusercontent.com/224027/39563840-66ca921e-4e77-11e8-9d3c-bb68d9c43db3.png)

**Comment by s3r8i0** [comment]
![gnome-shell-screenshot-h3eliz](https://user-images.githubusercontent.com/38960188/39597328-65eddca6-4eeb-11e8-9a03-46d18c3a620e.png)

Happens in Ubuntu 18.04 too.

**Comment by Gelmo** [comment]
I'm getting this on Windows, as well.

**Comment by KELiON** [comment]
@mybluevan @s3r8i0 you can find fix in #434.

**Comment by KELiON** [comment]
@Phosphor303 did you have another version installed or it is your first installation of Cerebro?

**Comment by Phosphor303** [comment]
@KELiON I had it installed years ago.

There was no Cerebro installation when I tried again recently, but dotfiles or preference settings may have persisted since my first try.

**Comment by mycraftmw** [comment]
It also shows on my Windows 10.

**Comment by kisnows** [comment]
![image](https://user-images.githubusercontent.com/9394000/41325387-906f9426-6eec-11e8-85cd-874bd5b8f648.png)
![image](https://user-images.githubusercontent.com/9394000/41325411-a921257a-6eec-11e8-92da-7544ac8f9a9f.png)

**Comment by kencano** [comment]
Same here.

**Comment by oguhpereira** [comment]
Could you test the new version?

@kencano @kisnows @mybluevan @dschuessler

**Comment by dubisdev** [comment]
I'm closing this error as it is related to the tracking feature that was recently removed. Please, tray with the latest version and if the problem persists we can open an updated issue.
