### ISSUE TITLE
window start error

### ISSUE THREAD

**Issue by gxy01** [cerebroapp/cerebro#467]
I'am using 0.32 on win 10.
When i first start app, alert many errors.

After some work, I find code error at ``main.development.js``:
```js
let trayIconSrc = `${__dirname}/tray_icon.png`
if (process.platform === 'darwin') {
  trayIconSrc = `${__dirname}/tray_iconTemplate@2x.png`
} else if (process.platform === 'win32') {
  trayIconSrc = `${__dirname}/tray_icon.ico`
}
```

On windows, I think the path should be '\\' instead of '/'.

I use `asar` change file packged in app.asar, Evething is fine.

**Comment by oguhpereira** [comment]
@gxy01 thanks for the comment
