### ISSUE TITLE
资源占用较大

### ISSUE THREAD

**Issue by YXH-YXH** [cerebroapp/cerebro#469]
此软件自己设置为开机启动并常驻后台，但是他的内存占用太大了
![12354](https://user-images.githubusercontent.com/35206235/41809297-d127bd52-771d-11e8-8477-b833091c8b0f.png)
内存占用近600MB！

**Comment by fzlinjianhui** [comment]
在issues里面看到中文,真好

**Comment by zhongbodong** [comment]
哈哈

**Comment by xiaotuotuo321** [comment]
请问这个占用内存问题如何解决，我这边是定期重启，想知道有没有什么自动化的方案，控制cerebro的内存占用。谢谢。

**Comment by oguhpereira** [comment]
this is a big problem that we intend to solve later on in the cerebroapp.

The electron itself has this feature of memory expenditure

**Comment by dubisdev** [comment]
I'm closing this as a duplicate of #118
