### ISSUE TITLE
Results not showing all the time

### ISSUE THREAD

**Issue by Itamar531** [cerebroapp/cerebro#471]
- [X ] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [ X] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Xubuntu 18.04
- **Cerebro.app version**: 0.3.2
- **Relevant information from devtools**: I enabled dev mode but I can't find it

## Issue
**Background**: installed Cerebro about four hours ago. It initially didn't work at all. I then changed "trackingEnabled" in the config file to "false", as suggested here which fixed that issue. Following, I installed two addons, cerebro-define and cerebro-imdb. I also installed cerebro-gkg which I promptly deleted, as it didn't work.

**Issue**: For some reason it is very inconsistent. Sometimes it'll work brilliantly, while sometimes I'd type something in the search bar (it'll even predict my query), but it won't show any results. I would then query the exact same thing several minutes later, and it will suddenly work. This happens around fifty percent of the time. 
Sometimes I even type something, delete it to type something else and again no results will show.

Thanks in advance !
This is really an amazing program !

**Comment by dignityinside** [comment]
+1 on Windows 10. Work only < 0.3.1

**Comment by osharifali** [comment]
Doesn't work on Windows 10 for me either -- the interface to search shows but no results are populated. I've been using 0.2.8 but that recently stopped working for me too. When I ins

**Comment by oguhpereira** [comment]
Hello everyone, this issue is very old and I don't know if you are still using cerebroapp. We went through some corrections worth testing the latest version. If you find a bug, we'll reopen it here.

@dignityinside @osharifali @Itamar531
