### ISSUE TITLE
Search result on the search bar

### ISSUE THREAD

**Issue by ujjwalbe** [cerebroapp/cerebro#473]
- [ x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x ] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Cerebro.app version**: 
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

I just figured out a feature that you could add , when search a query on cerebro we are redirect to open browser instead of that cerebro can show that result on right side of result panel. I find that it will be very much helpful. Thanks for your work.

**Comment by dubisdev** [comment]
Hi @ujjwalbe 

This feature is implemented in plugins like `cerebro-google` or `@cerebroapp/search`. Instead of selecting the results just press enter and the search is performed with the introduced term.
