### ISSUE TITLE
Plugins details not showing

### ISSUE THREAD

**Issue by oliverulerich** [cerebroapp/cerebro#476]
running latest ver 0.3.2 on Windows 10
after installing a few plugins, the app doesn't show the plugin details anymore when clicked "details" on plugin page even if the repo has readme and all. If I clean install the app again the problem disappears and then appears again, maybe a conscience of some plugins conflict, but strange.

**Comment by oguhpereira** [comment]
Hi @oliverulerich 

can you give more details and add some screenshots?

**Comment by oliverulerich** [comment]
I can't remember anything more (I stopped using cerebro two years ago)
