### ISSUE TITLE
Windows install without admin rights

### ISSUE THREAD

**Issue by hughwilliams94** [cerebroapp/cerebro#478]
- [X] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [X] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that 
- **OS version and name**: Windows 7
- **Cerebro.app version**: 0.3.2
- **Relevant information from devtools**: N/A

## Issue
I would like to be able to install Cerebro on a work computer on which I do not have administrator rights. Is there any reason the installer requires admin rights?

**Comment by oguhpereira** [comment]
@hughwilliams94 I think it is because of the indexing of the files, but we can check if there is a possibility of generating a portable version without this type of permission.
