### ISSUE TITLE
Project alive?

### ISSUE THREAD

**Issue by alabotski** [cerebroapp/cerebro#479]
Actually the question - Project alive?

**Comment by c10r0x** [comment]
I still use it sometimes, unfortunately it seems like the major development has stopped. Plugins never work.

**Comment by m3dragos** [comment]
I just recently stumbled upon this and love using it. Would be a shame for it to die...

**Comment by lebedov** [comment]
The [Ulauncher](https://ulauncher.io) has similar features and appears to be under active development.

**Comment by alabotski** [comment]
@lebedov There are only Linux =(

**Comment by alanaasmaa** [comment]
https://github.com/hainproject/hain/

This is one alternative but the development is slow also. But it seems not to be dead.

**Comment by rohanprasad** [comment]
Happy to contribute, but I am there are no contributing or development guide. Will try to dive into code, if anyone has good idea of the codebase and can help me please let me know.

**Comment by FreaKzero** [comment]
Thought many times since my error ticket in 2017 to contribute - but since there are 18 open PRs and most of the codebase is 2 years old i never bothered to contribute.

Using right now https://github.com/hainproject/hain as alternative - quite sad because i really liked cerebro.

**Comment by zachbryant** [comment]
What a shame this project is dead. Does not work on Ubuntu 18.04

**Comment by rogusdev** [comment]
Does anyone want to just fork it and start patching it then?

**Comment by dignityinside** [comment]
@zachbryant try to use this version https://github.com/KELiON/cerebro/releases/tag/v0.3.1, work for me on linux mint 19.1

**Comment by neederhow** [comment]
When i stell use ubuntu16 cerebro work very well in my laptop but when the release for linux become ".AppImage" i got so many ploblem that i have to give up.
When i upgrade to ubuntu18 it did not work.
When i use manjaro it did not work.
Now i have to use win7 ,it do work but plugins command dead and some other problem come.
So long Cerebro

**Comment by TobiasDev** [comment]
Ah,  too bad. :( I really liked this app, but looks like it is time for an alternative then.

**Comment by marcelloinfoweb** [comment]
Removi a muito tempo, o projeto é ótimo mas está abandonado, lamentável!

**Comment by alabotski** [comment]
I found a new solution for Linux - https://github.com/albertlauncher/albert

**Comment by in-in** [comment]
Looks like Albert's dead, too 😂
https://github.com/albertlauncher/albert/issues/867

It's probably an epidemic of launchers☠️

**Comment by alanaasmaa** [comment]
> Looks like Albert's dead, too 
> [albertlauncher/albert#867](https://github.com/albertlauncher/albert/issues/867)
> 
> It's probably an epidemic of launchers

https://github.com/oliverschwendener/ueli

Ueli is alive.

**Comment by oguhpereira** [comment]
pt: Estamos revivendo o projeto, conto com a ajuda da comunidade
en: We are reliving the project, I count on the help of the community

Thanks to everyone who supports the project

cc @alanaasmaa @in-in @alabotski @marcelloinfoweb @TobiasDev @neederhow @rogusdev @zachbryant @FreaKzero @rohanprasad @lebedov @m3dragos @c10r0x
