### ISSUE TITLE
[Request] Force browser window into foreground when searching google

### ISSUE THREAD

**Issue by ghost** [cerebroapp/cerebro#483]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: elementary OS 5.0 Juno (64bit)
- **Cerebro.app version**: cerebro-0.3.2-x86_64.AppImage
- **Browser version**: Chromium 71.0.3578.80 Built on Ubuntu

### Browser stays in background 🚫
**REPRO**

1. Open cerebro window
2. search google for "anyting"
3. Hit enter
4. minimize browser
5. Open cerebro window
6. search google for "anyting"
7. Hit enter

**EXPECTED**
Browser pops up on second google search

**ACTUAL**
Browser stays in background

**Comment by dubisdev** [comment]
I'm closing this issue as outdated. This has been fixed in newer versions (at least on Windows).

Take a look at the latest version and, if the problem persists, feel free to open a new issue.
