### ISSUE TITLE
Error on opening cerebro

### ISSUE THREAD

**Issue by anshuman73** [cerebroapp/cerebro#486]
- [ x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Ubuntu Budgie 18.04
- **Cerebro.app version**: 3.2
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue
I get this error when I installed the latest version (3.2) for Ubuntu Budgie. Happens when I open the app from my app menu. Also occurred when I pressed Ctrl + Space for the first time, howver was unable to reproduce afterwards.

```
Uncaught Exception:
TypeError: Cannot read property 'webContents' of undefined
    at EventEmitter.module.exports._electron.ipcMain.on (/opt/Cerebro/resources/app.asar/main.js:687:47)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at WebContents.<anonymous> (/opt/Cerebro/resources/electron.asar/browser/api/web-contents.js:247:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

**Comment by elvilio** [comment]
I have a similar problem upno opening Cerebro.app

- OS version and name: macOS Mojave 10.14.3
- Cerebro.app version: 3.2

Error shown on a default wondow:
`A JavaScript error occurred in the main process

Uncaught Exception:
TypeError: visitor(...).screenview is not a function
    at module.exports.exports.screenView.screenName (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/lib/trackEvent.js:31:15)
    at module.exports.exports.default (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/main/createWindow.js:166:3)
    at App.module.exports._electron.app.on (/Applications/Cerebro.app/Contents/Resources/app.asar/webpack:/app/main.development.js:38:16)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
`

**Comment by Anti-Antidote** [comment]
Same issue as @elvilio:

* Ubuntu 18.04 LTS
* GNOME
* Latest version as of 3/26/2019

**Comment by alex-i-n** [comment]
Same error as @elvilio and @Anti-Antidote:
- Ubuntu 18.10
- GNOME 3.30.1
- Cerebro 0.3.2

**Comment by phcamargo23** [comment]
Same error:
* Windows 10 Pro (1809)
* Cerebro 0.3.2

**Comment by CelsoSantos** [comment]
I'm facing the same o MacOS 10.14.4 with Cerebro 0.3.2

**Comment by MrFuri** [comment]
Same
- Ubuntu 18.04.2
- Cerebro 0.3.2

**Comment by zeitan** [comment]
Same
Ubuntu 16.04
Cerebro 0.3.2
````
Uncaught Exception:
TypeError: visitor(...).screenview is not a function
    at module.exports.exports.screenView.screenName (/opt/Cerebro/resources/app.asar/main.js:251:15)
    at module.exports.exports.default (/opt/Cerebro/resources/app.asar/main.js:915:30)
    at App.module.exports._electron.app.on (/opt/Cerebro/resources/app.asar/main.js:653:43)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
`````

**Comment by RoobieBoobieee** [comment]
Setting `trackingEnabled` to `false` fixed it for me in `~/.config/Cerebro/config.json`

**Comment by GabrielDuarteM** [comment]
Doing what @RoobieBoobieee suggested worked for me!

Also, I tried cloning the repo and running it locally, and then it works, even without setting `trackingEnabled` to `false`. Not sure what is causing the problem, I may take a look into it later, but it seems that this project, unfortunately, is pretty much abandoned, judging by the lack of response and the opened bugs :/

**Comment by zeitan** [comment]
trackingEnabled worked for me too!!

**Comment by birobirobiro** [comment]
Same error:

Windows 10 Home Single Language (18362)
Cerebro 0.3.2

**Comment by phanirithvij** [comment]
Where is the config file located on windows anyone?

**Comment by RoobieBoobieee** [comment]
`Windows: %APPDATA%/Cerebro/config.json`

It's in https://github.com/KELiON/cerebro/blob/master/README.md on line 68

**Comment by phanirithvij** [comment]
Thanks I was able to fix it.

**Comment by MycroftHolmes1989** [comment]
Had the same problem. Changing trackingEnabled flag works. However, the last release was 2 years, ago and the last commit was a year ago. Does anyone know if it is still being maintained?

**Comment by Anti-Antidote** [comment]
@MycroftHolmes1989 The repo owner has been working on some Cerebro plugins this last month, so maybe eventually he'll get back around to it

**Comment by Shekcon** [comment]
Install missing packages. It works for me
> sudo apt install libcanberra-gtk-module libcanberra-gtk3-module

**Comment by oguhpereira** [comment]
@anshuman73 thanks for this issue

I suppose it is duplicated #470 

I will close and move on to the other issue

thanks guys for the help

**Comment by CelsoSantos** [comment]
Does this mean there is new activity/development on Cerebro?

**Comment by oguhpereira** [comment]
@CelsoSantos sure 😄

**Comment by brkn** [comment]
For MacOs, config file is at `~/Library/Application Support/Cerebro/config.json`
