### ISSUE TITLE
No search results in Cerebro Windows

### ISSUE THREAD

**Issue by aman31saxena** [cerebroapp/cerebro#489]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **Windows 10**: 
- **Cerebro.app 0.3.1 **: 
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

I just installed Cerebro on Windows 10 from cerebroapp but I'm unable to see any external apps/files in the results. I installed some plugins( spotify, calculator etc) but it still didn't work (The calculator is also not working)
Also, the app freezes on 'Manage plugins'. I had to install the plugins via cmd.
 
![1](https://user-images.githubusercontent.com/37325169/59083014-3d756b00-8913-11e9-9120-b53ef088af6d.png)
![2](https://user-images.githubusercontent.com/37325169/59083015-3e0e0180-8913-11e9-8d56-b917f0fadebc.png)
![3](https://user-images.githubusercontent.com/37325169/59083016-3e0e0180-8913-11e9-9fe9-a3b533363f26.png)

**Comment by phanirithvij** [comment]
It worked for me after I restarted the app

**Comment by oguhpereira** [comment]
I believe this problem is with the cerebro plugins and not the core
