### ISSUE TITLE
How can I launch a program with admin right (Windows) ?

### ISSUE THREAD

**Issue by liu7yong** [cerebroapp/cerebro#490]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: windows 10
- **Cerebro.app version**: 0.3.2
- **Relevant information from devtools**: N/A

## Issue
There are some program I'd like to launch with admin right, how can I do that in windows?

**Comment by oguhpereira** [comment]
We have no solution for this at the moment, could give more details about these apps
