### ISSUE TITLE
Droplist not showing up sometimes

### ISSUE THREAD

**Issue by TraceLD** [cerebroapp/cerebro#493]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora 30, Pantheon Desktop Environment
- **Cerebro.app version**: 0.3.1 (AppImage)

## Issue
I think the best explanation is a video clip of the issue:
https://streamable.com/q21wv

**Comment by hitallow** [comment]
i have the same issue, i am using Linux Mint.

**Comment by iamsamuelhere** [comment]
I have the same issue on windows10

**Comment by dubisdev** [comment]
I'm closing this issue as outdated.

The video is no longer available so I can't see the problem.

Try with the latest version of Cerebro. If the problem persists you can open a new issue.

Thanks 🙌

David
