### ISSUE TITLE
Can't build cerebro on Fedora 30

### ISSUE THREAD

**Issue by marmalodak** [cerebroapp/cerebro#495]
- [X] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [X] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **Fedora 30**:
- **master**:
- **N/A**

    $ git clone http://github.com/KELiON/cerebro
    Cloning into 'cerebro'...
    warning: redirecting to https://github.com/KELiON/cerebro/
    remote: Enumerating objects: 6133, done.
    remote: Total 6133 (delta 0), reused 0 (delta 0), pack-reused 6133
    Receiving objects: 100% (6133/6133), 3.44 MiB | 5.13 MiB/s, done.
    Resolving deltas: 100% (3791/3791), done.
    $ cd cerebro/
    $ nodejs-yarn
    yarn install v1.13.0
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    info 7zip-bin-mac@1.0.1: The platform "linux" is incompatible with this module.
    info "7zip-bin-mac@1.0.1" is an optional dependency and failed compatibility check. Excluding it from installation.
    info 7zip-bin-win@2.0.2: The platform "linux" is incompatible with this module.
    info "7zip-bin-win@2.0.2" is an optional dependency and failed compatibility check. Excluding it from installation.
    info fsevents@1.1.1: The platform "linux" is incompatible with this module.
    info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    warning " > eslint-config-airbnb@15.0.2" has incorrect peer dependency "eslint@^3.19.0".
    warning "eslint-config-airbnb > eslint-config-airbnb-base@11.2.0" has incorrect peer dependency "eslint@^3.19.0".
    warning " > inject-loader@3.0.0" has incorrect peer dependency "webpack@^1 || ^2".
    warning " > mocha-webpack@0.7.0" has incorrect peer dependency "webpack@^1.12.13 || ^2.1.0-beta.15".
    [4/4] Building fresh packages...
    $ concurrently "node node_modules/fbjs-scripts/node/check-dev-engines.js package.json"
    [0] node node_modules/fbjs-scripts/node/check-dev-engines.js package.json exited with code 0
    Done in 6.27s.
    $ cd app
    $ nodejs-yarn
    yarn install v1.13.0
    [1/4] Resolving packages...
    [2/4] Fetching packages...
    info fsevents@1.1.1: The platform "linux" is incompatible with this module.
    info "fsevents@1.1.1" is an optional dependency and failed compatibility check. Excluding it from installation.
    [3/4] Linking dependencies...
    [4/4] Building fresh packages...
    error /tmp/cerebro/app/node_modules/ref: Command failed.
    Exit code: 1
    Command: node-gyp rebuild
    Arguments: 
    Directory: /tmp/cerebro/app/node_modules/ref
    Output:
    gyp info it worked if it ends with ok
    gyp info using node-gyp@3.8.0
    gyp info using node@10.16.3 | linux | x64
    gyp info spawn /usr/bin/python2
    gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
    gyp info spawn args   'binding.gyp',
    gyp info spawn args   '-f',
    gyp info spawn args   'make',
    gyp info spawn args   '-I',
    gyp info spawn args   '/tmp/cerebro/app/node_modules/ref/build/config.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
    gyp info spawn args   '-I',
    gyp info spawn args   '/mnt/myth/john/.node-gyp/10.16.3/include/node/common.gypi',
    gyp info spawn args   '-Dlibrary=shared_library',
    gyp info spawn args   '-Dvisibility=default',
    gyp info spawn args   '-Dnode_root_dir=/mnt/myth/john/.node-gyp/10.16.3',
    gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
    gyp info spawn args   '-Dnode_lib_file=/mnt/myth/john/.node-gyp/10.16.3/<(target_arch)/node.lib',
    gyp info spawn args   '-Dmodule_root_dir=/tmp/cerebro/app/node_modules/ref',
    gyp info spawn args   '-Dnode_engine=v8',
    gyp info spawn args   '--depth=.',
    gyp info spawn args   '--no-parallel',
    gyp info spawn args   '--generator-output',
    gyp info spawn args   'build',
    gyp info spawn args   '-Goutput_dir=.' ]
    gyp info spawn make
    gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
    make: Entering directory '/tmp/cerebro/app/node_modules/ref/build'
      CXX(target) Release/obj.target/binding/src/binding.o
    In file included from ../../nan/nan.h:192,
                     from ../src/binding.cc:8:
    ../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
    ../../nan/nan_maybe_43_inl.h:112:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
      112 |   return obj->ForceSet(isolate->GetCurrentContext(), key, value, attribs);
          |               ^~~~~~~~
    In file included from ../src/binding.cc:8:
    ../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
    ../../nan/nan.h:835:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
      835 |         v8::Isolate::GetCurrent(), target, func, argc, argv);
          |                                                            ^
    In file included from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:177:50: note: declared here
      177 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
          |                                                  ^~~~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
       91 |     __attribute__((deprecated(message))) declarator
          |                                          ^~~~~~~~~~
    In file included from ../src/binding.cc:8:
    ../../nan/nan.h:835:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
      835 |         v8::Isolate::GetCurrent(), target, func, argc, argv);
          |                                                            ^
    In file included from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:177:50: note: declared here
      177 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
          |                                                  ^~~~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
       91 |     __attribute__((deprecated(message))) declarator
          |                                          ^~~~~~~~~~
    In file included from ../src/binding.cc:8:
    ../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
    ../../nan/nan.h:850:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
      850 |         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
          |                                                              ^
    In file included from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:170:50: note: declared here
      170 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
          |                                                  ^~~~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
       91 |     __attribute__((deprecated(message))) declarator
          |                                          ^~~~~~~~~~
    In file included from ../src/binding.cc:8:
    ../../nan/nan.h:850:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
      850 |         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
          |                                                              ^
    In file included from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:170:50: note: declared here
      170 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
          |                                                  ^~~~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
       91 |     __attribute__((deprecated(message))) declarator
          |                                          ^~~~~~~~~~
    In file included from ../src/binding.cc:8:
    ../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
    ../../nan/nan.h:865:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
      865 |         v8::Isolate::GetCurrent(), target, method, argc, argv);
          |                                                              ^
    In file included from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:163:50: note: declared here
      163 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
          |                                                  ^~~~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
       91 |     __attribute__((deprecated(message))) declarator
          |                                          ^~~~~~~~~~
    In file included from ../src/binding.cc:8:
    ../../nan/nan.h:865:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
      865 |         v8::Isolate::GetCurrent(), target, method, argc, argv);
          |                                                              ^
    In file included from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:163:50: note: declared here
      163 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
          |                                                  ^~~~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
       91 |     __attribute__((deprecated(message))) declarator
          |                                          ^~~~~~~~~~
    In file included from ../src/binding.cc:8:
    ../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
    ../../nan/nan.h:1479:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     1479 |     ));
          |     ^
    In file included from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:177:50: note: declared here
      177 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
          |                                                  ^~~~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
       91 |     __attribute__((deprecated(message))) declarator
          |                                          ^~~~~~~~~~
    In file included from ../src/binding.cc:8:
    ../../nan/nan.h:1479:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     1479 |     ));
          |     ^
    In file included from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:177:50: note: declared here
      177 |                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
          |                                                  ^~~~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:91:42: note: in definition of macro ‘NODE_DEPRECATED’
       91 |     __attribute__((deprecated(message))) declarator
          |                                          ^~~~~~~~~~
    In file included from ../src/binding.cc:8:
    ../../nan/nan.h: In function ‘void Nan::AsyncQueueWorker(Nan::AsyncWorker*)’:
    ../../nan/nan.h:1732:62: warning: cast between incompatible function types from ‘void (*)(uv_work_t*)’ {aka ‘void (*)(uv_work_s*)’} to ‘uv_after_work_cb’ {aka ‘void (*)(uv_work_s*, int)’} [-Wcast-function-type]
     1732 |     , reinterpret_cast<uv_after_work_cb>(AsyncExecuteComplete)
          |                                                              ^
    ../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::WriteObject(Nan::NAN_METHOD_ARGS_TYPE)’:
    ../src/binding.cc:229:54: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class Nan::Persistent<v8::Object>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
      229 |     memcpy(pptr, &p2, sizeof(Nan::Persistent<Object>));
          |                                                      ^
    In file included from ../../nan/nan.h:313,
                     from ../src/binding.cc:8:
    ../../nan/nan_persistent_12_inl.h:12:40: note: ‘class Nan::Persistent<v8::Object>’ declared here
       12 | template<typename T, typename M> class Persistent :
          |                                        ^~~~~~~~~~
    ../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::ReadPointer(Nan::NAN_METHOD_ARGS_TYPE)’:
    ../src/binding.cc:253:38: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
      253 |   size_t size = info[2]->Uint32Value();
          |                                      ^
    In file included from /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:26,
                     from /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:63,
                     from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:2477:47: note: declared here
     2477 |   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
          |                                               ^~~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
      324 |   declarator __attribute__((deprecated(message)))
          |   ^~~~~~~~~~
    ../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::WriteInt64(Nan::NAN_METHOD_ARGS_TYPE)’:
    ../src/binding.cc:360:29: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
      360 |     String::Utf8Value str(in);
          |                             ^
    In file included from /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:26,
                     from /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:63,
                     from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:2892:28: note: declared here
     2892 |                   explicit Utf8Value(Local<v8::Value> obj));
          |                            ^~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
      324 |   declarator __attribute__((deprecated(message)))
          |   ^~~~~~~~~~
    ../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::WriteUInt64(Nan::NAN_METHOD_ARGS_TYPE)’:
    ../src/binding.cc:435:29: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
      435 |     String::Utf8Value str(in);
          |                             ^
    In file included from /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:26,
                     from /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:63,
                     from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:2892:28: note: declared here
     2892 |                   explicit Utf8Value(Local<v8::Value> obj));
          |                            ^~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
      324 |   declarator __attribute__((deprecated(message)))
          |   ^~~~~~~~~~
    ../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::ReinterpretBuffer(Nan::NAN_METHOD_ARGS_TYPE)’:
    ../src/binding.cc:497:38: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
      497 |   size_t size = info[1]->Uint32Value();
          |                                      ^
    In file included from /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:26,
                     from /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:63,
                     from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:2477:47: note: declared here
     2477 |   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
          |                                               ^~~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
      324 |   declarator __attribute__((deprecated(message)))
          |   ^~~~~~~~~~
    ../src/binding.cc: In function ‘Nan::NAN_METHOD_RETURN_TYPE {anonymous}::ReinterpretBufferUntilZeros(Nan::NAN_METHOD_ARGS_TYPE)’:
    ../src/binding.cc:526:44: warning: ‘uint32_t v8::Value::Uint32Value() const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
      526 |   uint32_t numZeros = info[1]->Uint32Value();
          |                                            ^
    In file included from /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:26,
                     from /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:63,
                     from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:2477:47: note: declared here
     2477 |   V8_DEPRECATED("Use maybe version", uint32_t Uint32Value() const);
          |                                               ^~~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
      324 |   declarator __attribute__((deprecated(message)))
          |   ^~~~~~~~~~
    ../src/binding.cc: In function ‘void init(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’:
    ../src/binding.cc:619:11: error: ‘class v8::Object’ has no member named ‘ForceSet’
      619 |   target->ForceSet(Nan::New<v8::String>("endianness").ToLocalChecked(), Nan::New<v8::String>(CheckEndianness()).ToLocalChecked(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
          |           ^~~~~~~~
    ../src/binding.cc:620:11: error: ‘class v8::Object’ has no member named ‘ForceSet’
      620 |   target->ForceSet(Nan::New<v8::String>("NULL").ToLocalChecked(), WrapNullPointer(), static_cast<PropertyAttribute>(ReadOnly|DontDelete));
          |           ^~~~~~~~
    In file included from ../src/binding.cc:6:
    ../src/binding.cc: At global scope:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:573:43: warning: cast between incompatible function types from ‘void (*)(Nan::ADDON_REGISTER_FUNCTION_ARGS_TYPE)’ {aka ‘void (*)(v8::Local<v8::Object>)’} to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
      573 |       (node::addon_register_func) (regfunc),                          \
          |                                           ^
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:607:3: note: in expansion of macro ‘NODE_MODULE_X’
      607 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
          |   ^~~~~~~~~~~~~
    ../src/binding.cc:636:1: note: in expansion of macro ‘NODE_MODULE’
      636 | NODE_MODULE(binding, init);
          | ^~~~~~~~~~~
    In file included from /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:63,
                     from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = node::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)]’:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/node_object_wrap.h:84:78:   required from here
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<node::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<node::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
     9502 |                reinterpret_cast<Callback>(callback), type);
          |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]’:
    ../../nan/nan_object_wrap.h:66:61:   required from here
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
    In file included from ../../nan/nan.h:2218,
                     from ../src/binding.cc:8:
    ../../nan/nan_weak.h: In instantiation of ‘Nan::WeakCallbackInfo<P>::WeakCallbackInfo(Nan::Persistent<v8::Value>*, Nan::WeakCallbackInfo<P>::Callback, void*, void*, void*) [with T = void; Nan::WeakCallbackInfo<P>::Callback = void (*)(const Nan::WeakCallbackInfo<void>&)]’:
    ../../nan/nan_weak.h:264:12:   required from ‘void Nan::Persistent<T, M>::SetWeak(P*, typename Nan::WeakCallbackInfo<P>::Callback, Nan::WeakCallbackType) [with P = void; T = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>; typename Nan::WeakCallbackInfo<P>::Callback = void (*)(const Nan::WeakCallbackInfo<void>&); Nan::WeakCallbackType = v8::WeakCallbackType]’
    ../src/binding.cc:228:77:   required from here
    ../../nan/nan_weak.h:58:16: warning: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of type ‘class v8::Persistent<v8::Value>’ with no trivial copy-assignment; use copy-assignment or copy-initialization instead [-Wclass-memaccess]
       58 |     std::memcpy(&persistent_, persistent, sizeof (v8::Persistent<v8::Value>));
          |     ~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /mnt/myth/john/.node-gyp/10.16.3/include/node/node.h:63,
                     from ../src/binding.cc:6:
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:685:35: note: ‘class v8::Persistent<v8::Value>’ declared here
      685 | template <class T, class M> class Persistent : public PersistentBase<T> {
          |                                   ^~~~~~~~~~
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h: In instantiation of ‘void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::WeakCallbackInfo<void>; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::WeakCallbackInfo<void> >&)]’:
    ../../nan/nan_weak.h:268:35:   required from ‘void Nan::Persistent<T, M>::SetWeak(P*, typename Nan::WeakCallbackInfo<P>::Callback, Nan::WeakCallbackType) [with P = void; T = v8::Object; M = v8::NonCopyablePersistentTraits<v8::Object>; typename Nan::WeakCallbackInfo<P>::Callback = void (*)(const Nan::WeakCallbackInfo<void>&); Nan::WeakCallbackType = v8::WeakCallbackType]’
    ../src/binding.cc:228:77:   required from here
    /mnt/myth/john/.node-gyp/10.16.3/include/node/v8.h:9502:16: warning: cast between incompatible function types from ‘v8::WeakCallbackInfo<Nan::WeakCallbackInfo<void> >::Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<Nan::WeakCallbackInfo<void> >&)’} to ‘Callback’ {aka ‘void (*)(const v8::WeakCallbackInfo<void>&)’} [-Wcast-function-type]
     9502 |                reinterpret_cast<Callback>(callback), type);
          |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    make: *** [binding.target.mk:103: Release/obj.target/binding/src/binding.o] Error 1
    make: Leaving directory '/tmp/cerebro/app/node_modules/ref/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
    gyp ERR! System Linux 5.2.9-200.fc30.x86_64
    gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /tmp/cerebro/app/node_modules/ref
    gyp ERR! node -v v10.16.3
    gyp ERR! node-gyp -v v3.8.0
    gyp ERR! not ok
    info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by fanat98** [comment]
downgrade your node version to 8

**Comment by marmalodak** [comment]
Thanks @fanat98. 

I started writing an rpm .spec file. I don't want to download a local node version and require that in the .spec file. 

Upgrading to the current node is not in the works?

**Comment by fanat98** [comment]
@marmalodak You're welcome.
unfortunately this project has not been updated for 1 year now

**Comment by dubisdev** [comment]
Cerebro is now using node 16

We are closing this as an old issue. Try v0.7.1 and, if the issue persists, please open other issue
