### ISSUE TITLE
Link to Download Cerebro Windows 0.3.3 version

### ISSUE THREAD

**Issue by mmelnic** [cerebroapp/cerebro#496]
Since project is dead, I compiled 0.3.3 version from master, that fixed some bugs with startup 

https://www.dropbox.com/s/qwbfs3n1cqas94n/Cerebro%20Setup%200.3.3.exe?dl=0
- **OS Windows**
- **Cerebro.app 0.3.3**

**Comment by AugustasV** [comment]
For me it worked to download directly from page: https://github.com/KELiON/cerebro/releases/download/v0.3.1/cerebro-setup-0.3.1.exe

**Comment by ganderm** [comment]
> For me it worked to download directly from page: https://github.com/KELiON/cerebro/releases/download/v0.3.1/cerebro-setup-0.3.1.exe

that link very clearly says **0.3.1**, the issue is about **0.3.3**

**Comment by brandbrilliance** [comment]
Thanks. This is nice with the system tray, etc. However only the search and calculation plugins work. If I try a currency converted it doesn't work at all. Not even searching for files. Just Apps and Calculations and weather work. Strange. Looked so promising. I miss MacOS at work.

**Comment by oguhpereira** [comment]
thanks for the issue @mmelnic 

use the link for the releases at the moment. We will update a new version soon
