### ISSUE TITLE
Cerebro for Android?

### ISSUE THREAD

**Issue by ShinobiWPS** [cerebroapp/cerebro#497]
- [ ] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 
- **Cerebro.app version**: 
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

Any plan to write Cerebro App for Android?

**Comment by good-lly** [comment]
you can try https://play.google.com/store/apps/details?id=com.sentienhq.launcher&hl=en_US&gl=US or kiss launcher

**Comment by oguhpereira** [comment]
at the moment we do not intend to launch any mobile version
