### ISSUE TITLE
Electron Version too Old

### ISSUE THREAD

**Issue by Msouza91** [cerebroapp/cerebro#499]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora Workstation 31
- **Cerebro.app version**: 0.32
Dump when I try to start the appimg from CLI:
```
installed: X-AppImage-BuildId=847a0770-d98f-11a7-0ebd-e5b83ffea09e image: X-AppImage-BuildId=847a0770-d98f-11a7-0ebd-e5b83ffea09e
A JavaScript error occurred in the main process
Uncaught Exception:
Error: ENOENT: no such file or directory, open '/home/marco/.config/Cerebro/config.json'
    at Object.fs.openSync (fs.js:558:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.writeFileSync (fs.js:1233:33)
    at Object.get (/tmp/.mount_nnFS67/usr/bin/resources/app.asar/main.js:162:18)
    at Object.module.exports.Object.defineProperty.value (/tmp/.mount_nnFS67/usr/bin/resources/app.asar/main.js:642:24)
    at __webpack_require__ (/tmp/.mount_nnFS67/usr/bin/resources/app.asar/main.js:21:30)
    at /tmp/.mount_nnFS67/usr/bin/resources/app.asar/main.js:64:18
    at Object.<anonymous> (/tmp/.mount_nnFS67/usr/bin/resources/app.asar/main.js:67:10)
    at Object.<anonymous> (/tmp/.mount_nnFS67/usr/bin/resources/app.asar/main.js:3738:3)
    at Module._compile (module.js:571:32)

(cerebro:56588): Pango-ERROR **: 14:53:06.510: Harfbuzz version too old (1.3.1)

[1]    56588 trace trap (core dumped)  ./cerebro-0.3.2-x86_64\(1\).AppImage
```
## Issue
I'm trying to run cerebro from the App Image, but it didn't start from the shortcut 
then I tryed to run it from CLI and got the error above, looked around the 
internet and it seems that one package inside the image is not 
compatible with my system and it should be updated by the devs...
Is it correct? Is this a known issue? Is there any workaround?
Are there plans to support my distro?
Thanks for taking the time to read this.

**Comment by Aberrantfox** [comment]
Same issue here

**Comment by simonbcn** [comment]
Arch Linux
Same problem

**Comment by jdewfiez** [comment]
the developer seems not to be active on this project anymore.

**Comment by eggehad** [comment]
Same issue for me too.  Frustrating.

**Comment by xiantang** [comment]
same issue...

**Comment by xiantang** [comment]
Ubuntu

**Comment by leorocco** [comment]
Ubuntu 20.04. Same problem.

**Comment by zeal2end** [comment]
Same problem I think developers have left the project so need to switch something else...

**Comment by ThePrincelle** [comment]
Exactly the same issue on my side, can't believe that this hasn't been fixed yet.

**Comment by vrmartins** [comment]
Linux Mint 20, same problem. There is an solution in the PR #504

**Comment by vrmartins** [comment]
Linux Mint 20, same problem. There is a solution in the PR #504

**Comment by MrPancakes39** [comment]
Ubuntu 20.04 same issue

**Comment by FrancescoSaverioZuppichini** [comment]
same

**Comment by oguhpereira** [comment]
Updated to latest version
