### ISSUE TITLE
Displays double items.

### ISSUE THREAD

**Issue by rajeshisnepali** [cerebroapp/cerebro#503]
![2020-04-22_13-43](https://user-images.githubusercontent.com/23610013/79933276-50cbef00-846f-11ea-9a97-f75e528beb64.png)

> It shows two items for a single item.

**Comment by oguhpereira** [comment]
@rajeshisnepali  Is this error happening only for this item? maybe you should have 2 shortcut icons

**Comment by rajeshisnepali** [comment]
Maybe, but I'm not so sure as this is a year-old issue.

**Comment by oguhpereira** [comment]
@rajeshisnepali all right, I will close this issue at moment. If the error happens again please re-open 😄 

thank's
