### ISSUE TITLE
 It seems that the author does not intend to maintain the project, I recommend another similar project "utools".

### ISSUE THREAD

**Issue by lyandzao** [cerebroapp/cerebro#506]
here is the link, https://www.u.tools/

**Comment by igaurab** [comment]
@lyandzao how do we change the language to english? The app seems good

**Comment by lyandzao** [comment]
> @lyandzao how do we change the language to english? The app seems good

I asked the authors in the community, and they seemed to be too busy to do the translation work, which may be launched as a plug-in later

**Comment by Scupake** [comment]
What about we just fork this project.

**Comment by lyandzao** [comment]
This project is not open source in current version because this is a funded team project, it just open the api to the developer,   maybe in the future there will be paid services like cloud storage but most of the features are free

**Comment by Scupake** [comment]
I was talking about Cerebro, seems like a waste of time and effort to just let it die. imo we should find someone willing to maintain Cerebro instead of just using something else, especially if it's not open source.

**Comment by wcasanova** [comment]
Try Ulauncher

**Comment by rawsta** [comment]
An Alternative: https://github.com/oliverschwendener/ueli

**Comment by R-Bower** [comment]
Still looking for a solid linux alternative.  Ulauncher is ok but it doesn't support full-text-search like cerebro.

**Comment by rawsta** [comment]
> Still looking for a solid linux alternative. Ulauncher is ok but it doesn't support full-text-search like cerebro, and requires you to prefix each command with a configured keyword that triggers it.

Have you tried ROFI? https://github.com/davatorium/rofi
It needs some configuration but is quite a good launcher for me.

**Comment by SquirrelsMcGee** [comment]
Wouldn't PowerToys Run be a suitable alternative for this? So long as you're running Windows 10 at least. https://github.com/microsoft/PowerToys/wiki/PowerToys-Run-Overview

Or Wox, what is effectively the same thing, and appears to allow for Plugin support. https://github.com/Wox-launcher/Wox

According to https://github.com/microsoft/PowerToys/issues/3200#issuecomment-631130861 this feature will be added to PowerToys Run in the future

**Comment by sancarn** [comment]
[LaunchMenu](https://launchmenu.github.io/) is only in the working stages but we hope to make a cerebro plugin, which allow [any cerebro plugin to run in LaunchMenu](https://github.com/LaunchMenu/LaunchMenu/issues/94).

Currently we have few maintainers though, so would be happy for any help!

**Comment by oguhpereira** [comment]
I used the cerebroapp during my college years and thought it was an amazing application. Today I'm able to help a little more for this application and I hope I can contribute to the project.

I believe that we have many advantages with this application and probably the ones you mentioned have different ones.

Today we are in need of help to try to update and resolve the bugs of this project, we are fighting against time in our free time.

Who can contribute we sincerely thank you
