### ISSUE TITLE
A javaScript error occurred in the main process

### ISSUE THREAD

**Issue by Gamerbiomek2** [cerebroapp/cerebro#507]
the image I provide should explain what is being caused.
![Cerebro app javaScript error](https://user-images.githubusercontent.com/22333494/89722238-4f3e1c80-d9b5-11ea-915d-c752430bafc0.png)

**Comment by Qoyyuum** [comment]
I just downloaded and installed mine as well today. First time usage and sees a different issue as OP but related.

![image](https://user-images.githubusercontent.com/971309/89757574-3dc15580-db18-11ea-8f6f-36d46b4e903d.png)

**Comment by FearNaBoinne** [comment]
Same here... First run I got the 2nd error, after that the first on each start, and although ctrl-space works, nothing else does!

**Comment by YOUSIKI** [comment]
I just met the same error.
Is there any workaround so far?

**Comment by dubisdev** [comment]
I'm closing this as it is an issue related to the tracking feature that has been removed.
