### ISSUE TITLE
i have a error

### ISSUE THREAD

**Issue by Nikanubu2020** [cerebroapp/cerebro#509]
my error after type yarn in directory
 ./app 

make: *** [binding.target.mk:103: Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/mohammad/cerebro/app/node_modules/ref/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/mohammad/.config/yarn/global/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Linux 5.4.0-42-generic
gyp ERR! command "/usr/bin/node" "/home/mohammad/.yarn/bin/node-gyp" "rebuild"
gyp ERR! cwd /home/mohammad/cerebro/app/node_modules/ref
gyp ERR! node -v v10.19.0
gyp ERR! node-gyp -v v7.0.0
gyp ERR! not ok

**Comment by oguhpereira** [comment]
try to run the cerebroapp in version 8 of the node

@Nikanubu2020

**Comment by oguhpereira** [comment]
closed at the moment for no interaction
