### ISSUE TITLE
chrome extension

### ISSUE THREAD

**Issue by acornejo** [cerebroapp/cerebro#51]
Is it feasible to package this as a chrome extension?

This would make it possible to run on chromeOS too.

**Comment by KELiON** [comment]
@acornejo theoretically yes, but we should bundle it with web-APIs only, without native things like files/apps search, contacts, etc.

What would you like to see in chrome extension?

**Comment by ibbatta** [comment]
@KELiON I'd like to see:

- translations
- gif finder
- terminal (maybe)

**Comment by KELiON** [comment]
@ibbatta terminal in chrome extension is impossible, but gif/emoj/translations/google maps could work. I'll about it, but not in few closest releases, because it needs a lot of work. Thanks for idea!

**Comment by ibbatta** [comment]
@KELiON In fact, I had written "maybe". Let this child dream free. Let this child to dream ahahah
Sure, those are just some "tips / preferences"

**Comment by acornejo** [comment]
Even the examples you mention would be doable in a chrome extension, but they would require a separate cerebro plugin:

- files: https://developer.chrome.com/apps/fileSystem
- apps: https://developer.chrome.com/extensions/management
- contacts: https://developers.google.com/people/

Of course not all is possible though (I.e. terminal) but I believe we could get pretty close.

**Comment by ibbatta** [comment]
@acornejo yes i (sadly) know about terminal. I was warking on a chrome extensione in these days for my society, so tell me if you need any help :)

**Comment by oguhpereira** [comment]
@acornejo Thanks for the sugestion

it would be very interesting, but not for. I'm closing for that reason
