### ISSUE TITLE
win 10 2004 после обновления системы, перестала запускаться.

### ISSUE THREAD

**Issue by Azmandios** [cerebroapp/cerebro#511]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: win 10  2004
- **Cerebro.app version**: 0.3.2
- **Relevant information from devtools** _(See above how to open it)_: N/A

## Issue

Не запускается после обновления, сразу падает в ошибку.  Попробовал установить на домашнем ПК с 2004 версией, та же ошибка.  Скрины ошибки прилаю.

это ошибка при старте:
![2020-09-03_202533](https://user-images.githubusercontent.com/23055853/92150187-b8377980-ee27-11ea-8d60-d1f9799bcee2.jpg)
ото окно программы:
![2020-09-03_202627](https://user-images.githubusercontent.com/23055853/92150268-d7360b80-ee27-11ea-9353-96fba3b0be89.jpg)

**Comment by dubisdev** [comment]
This is an error related to tracking functionality. It was removed in [`v0.7.0`](https://github.com/cerebroapp/cerebro/releases/tag/v0.7.0) so we are closing this.
