### ISSUE TITLE
Make analytics opt-in

### ISSUE THREAD

**Issue by edwardgalligan** [cerebroapp/cerebro#512]
- [ ] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 10.15.6
- **Cerebro.app version**: 0.3.0 (latest from https://cerebroapp.com/ )
- **Relevant information from devtools** N/A

## Issue

I just installed Cerebro and the app immediately tried to open multiple connections to Google.com & Google Analytics. This type of functionality should at the very least be configurable; better yet opt-in. An onboarding screen with this option would be a good UX flow.

Either way, it should definitely not be making such connections on first-run. This is a pretty bad first-impression of the app for new users.

**Comment by dubisdev** [comment]
Hi @oguhpereira 
I have been reading this issue and I think we should remove analytics because:

1. None of the current team members is able to access the analytics so they are useless
2. Crash reports are OK but, why do we want to collect analytics?

I'll open a PR for removing them 🚮

**Comment by gerroon** [comment]
Hi,

Is this implemented ? I do not see any settings to disable tracking, and it still connects to GA regularly, at least on Windows.

**Comment by dubisdev** [comment]
Hi @gerroon all the code related to analytics was removed in #577 (this includes the options to disable them, as they don't exist)

Make sure you are using the latest [cerebro version](https://github.com/cerebroapp/cerebro/releases/latest)

**Maybe some of the plugins you are using are sending data to GA? I'm 100% sure Cerebro is not.**

The only reports that exist are uploaded to crashes.cerebroapp.com (these are crash reports, not including any analytics) in https://github.com/cerebroapp/cerebro/blob/03253640d2b80dc4931bb66de198957a2613719f/app/main.development.js#L33

BTW, that reports are not being used as nobody of the current development team has access to that domain.

**Comment by gerroon** [comment]
Thanks for the update.

This is a fresh install and no plugin is installed. It is not connect to GA (no packets) but it does a domain query to it. I will investigate it further.

**Comment by gerroon** [comment]
I also this querried by cerebro? suggestqueries.google.com

**Comment by dubisdev** [comment]
Hi @gerroon , yes! That is the autocomplete endpoint for the search plugin. Here you can see it:

https://github.com/cerebroapp/search/blob/363261473d3090937b141833ccbcd1e50a1b4e94/src/handlers/google.tsx#L6

In the first run Cerebro installs some plugins to make it easy to start using it.

You can see them here:

https://github.com/cerebroapp/cerebro/blob/03253640d2b80dc4931bb66de198957a2613719f/app/plugins/core/plugins/initializeAsync.js#L14

BTW you can configure the search engine you are using or simply remove the plugin.

Hope this helps!

**Comment by gerroon** [comment]
@dubisdev  Thanks for the info and heads up. This looks great finally  a cross platform desktop search utility for multiple platforms.
