### ISSUE TITLE
Is the project still active?

### ISSUE THREAD

**Issue by purezen** [cerebroapp/cerebro#513]
Just checked the project. However, I see the code-base is inactive since two years.

Is the project still under active development?

**Comment by muava12** [comment]
same question

**Comment by skoll43** [comment]
powertoys is doing something very similar...

**Comment by oguhpereira** [comment]
Hi

yes, we are working with him again this year @purezen @muava12 @skoll43 

Accepting prs to fix bugs and add improvements
