### ISSUE TITLE
unusable app after running `yarn dev`

### ISSUE THREAD

**Issue by rublev** [cerebroapp/cerebro#526]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: big sur 11.2 on macbook air m1
- **Cerebro.app version**: no idea, its the latest code, cant even open preferences or anything

## Issue
after running `yarn dev` a little white spotlight-like bar pops up, but i cant type in it. i see the cerebro icon in the menubar but i cant open preferences or fetch new versions or anything. the whole thing errors out

![image](https://user-images.githubusercontent.com/470273/108188474-a13aca00-70dd-11eb-9814-6e49f8e071bf.png)

**Comment by oguhpereira** [comment]
@rublev what version of node are you using?

**Comment by aidanjacobson** [comment]
I am also having this issue, with output of `node --version` being v14.10.1

**Comment by oguhpereira** [comment]
at the moment to run the brain I have installed the dependencies in version 8, to run I use the `yarn run dev` in version 14, you can try to do that!

Let's update the brain for newer versions of electron and node, all a matter of time, we are coming back now

**Comment by rublev** [comment]
> @rublev what version of node are you using?

either v10 latest or v8 latest

**Comment by oguhpereira** [comment]
@rublev I'm running cerebro app today with that by performing the following steps

```bash
nvm use 14
git clone https://github.com/cerebroapp/cerebro.git
cd cerebro
yarn
cd ./app
nvm use 8
yarn
cd ..
yarn build
yarn run dev
```

I received the same error, but my application is running
![image](https://user-images.githubusercontent.com/24482087/109748698-0e5b5e80-7bb8-11eb-9d5c-0d6af4b86b21.png)

**Comment by rublev** [comment]
> @rublev I'm running cerebro app today with that by performing the following steps
> 
> ```shell
> nvm use 14
> git clone https://github.com/cerebroapp/cerebro.git
> cd cerebro
> yarn
> cd ./app
> nvm use 8
> yarn
> cd ..
> yarn build
> yarn run dev
> ```
> 
> I received the same error, but my application is running
> ![image](https://user-images.githubusercontent.com/24482087/109748698-0e5b5e80-7bb8-11eb-9d5c-0d6af4b86b21.png)
> 
> ### Edit
> Try to use this in the last version
> 
> ```shell
> nvm use 14
> git clone https://github.com/cerebroapp/cerebro.git
> cd cerebro
> yarn
> cd ./app
> yarn
> cd ..
> yarn build
> yarn run dev
> ```

Thanks bro I'll give that a try
