### ISSUE TITLE
 Harfbuzz version too old (1.3.1)

### ISSUE THREAD

**Issue by sergiobgar** [cerebroapp/cerebro#527]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [ ] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS versionandname**:  Debian testing
- **Cerebro.app version**:  latest version 

## Issue
This error show in the start of app and exit.
(cerebro:50485): Pango-ERROR **: 22:43:15.104: Harfbuzz version too old (1.3.1)

**Comment by itsnothingg** [comment]
same here

**Comment by weiameili** [comment]
Hi, there was an issue with electron where it used an old version oh Harfbuzz which was fixed. However, the developer of cerebro will have to use a newer electron version. See [this issue](https://github.com/electron/electron/issues/20348) for further information.

**Comment by oguhpereira** [comment]
what version of the node are you running? on ubuntu it is ok

**Comment by sergiobgar** [comment]
I have 14.16.0 version of node.

**Comment by WrathOP** [comment]
How to fix this issue?

**Comment by weiameili** [comment]
Hi, firstly I doubt the version of node installed on your computer matters here. Rather, it is the version of electron that this package depends on. The latest stable version of electron is 12.x.x I think. I found this in the yarn.lock file in this repository:
```
"@electron/universal@1.0.4":
  version "1.0.4"
  resolved "https://registry.yarnpkg.com/@electron/universal/-/universal-1.0.4.tgz#231ac246c39d45b80e159bd21c3f9027dcaa10f5"
  integrity sha512-ajZoumi4XwqwmZe8YVhu4XGkZBCPyWZsVCQONPTIe9TUlleSN+dic3YpXlaWcilx/HOzTdldTKtabNTeI0gDoA==
  dependencies:
    "@malept/cross-spawn-promise" "^1.1.0"
    asar "^3.0.3"
    debug "^4.3.1"
    dir-compare "^2.4.0"
    fs-extra "^9.0.1"
```
I don't know much about yarn but from this I can infer rhat the version of electron used is really old.

The only way to solve this I guess would be to migrate the project to a newer version of electron.

**Comment by oguhpereira** [comment]
Thanks for the feedback I'm analyzing the electron update

I asked about the version of the node because for a long time it was a problem here in this project. Using the latest version of the node, this problem was no longer happening for me

**Comment by kaaninho** [comment]
I also have this problem. Is there a fix that I can do locally so I don't have to wait for a new release?

**Comment by dantehemerson** [comment]
Same here

**Comment by hwiorn** [comment]
Got the same error in v0.3.1 downloaded from the site. But no error in v0.4.0 I built directly. I think that need a new v0.4.0 AppImage.

**Comment by jainal09** [comment]
How did you built it @hwiorn

**Comment by hwiorn** [comment]
@jainal09 

Here is a workaround for building electron-builder with v0.4.0 tag. But I recommend using just latest commit already fixed instead of v0.4.0.

## v0.4.0 tag
```sh
git clone https://github.com/cerebroapp/cerebro.git -b v0.4.0
cd cerebro
sed -i 's/"0.3.3"/"0.4.0"/g; s/^\( *"electron-updater": \)".*",$/\1"^4.0.0",/g' app/package.json
sed -i 's/"0.3.3"/"0.4.0"/g; s/^\( *"build": .*yarn minify\)",$/\1 \&\& electron-builder",/g' package.json
(yarn; cd app; yarn); yarn build
./release/Cerebro-0.4.0.AppImage
```

## Using latest commit
```sh
git clone https://github.com/cerebroapp/cerebro.git
cd cerebro
sed -i 's/"0.3.3"/"0.4.0"/g' app/package.json
sed -i 's/"0.3.3"/"0.4.0"/g' package.json
(yarn; cd app; yarn); yarn build
./release/Cerebro-0.4.0.AppImage
```

**Comment by travizanutto** [comment]
@hwiorn 
Hey, sorry to bother but I manage to build and install the .deb in my Ubuntu 21.04, but the Ctrl+Space doesn't work, I can't change it in the settings and the only plugin that works is the Google one.
Have you faced these issues?

**Comment by hwiorn** [comment]
@travizanutto
No, I didn't.

But `Ctrl+space` key didn't work when I run cerebro  I built at first time.
You can see cerebro icon in system tray if you run it once. And click the `Toggle cerebro` in context menu.

If cerebro app doesn't show, you need to check what happened inside it. Type and run cerebro in terminal directly and check logs out.

You should check cerebro which work correctly using `yarn run dev` before install on your system.

**Comment by travizanutto** [comment]
I get this error:
$ sudo yarn dev build  
yarn run v1.22.10
$ concurrently --kill-others "yarn run hot-server" "yarn run start-hot" build
[2] /bin/sh: 1: build: not found
[2] build exited with code 127
--> Sending SIGTERM to other processes..
[0] yarn run hot-server exited with code null
[1] yarn run start-hot exited with code null
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by hwiorn** [comment]
@travizanutto Run `yarn run dev` without `sudo`.

**Comment by imabp** [comment]
Hey @hwiorn  I am facing this syntax error, when I tried to run the v0.4.0 AppImage. 
Is it known issue? Or something wrong I am doing!

![image](https://user-images.githubusercontent.com/53480076/148634559-0d60a4b2-0a53-4f7a-8548-17a6c63fc87b.png)
