### ISSUE TITLE
0.4.0 release doesn't have binaries/packed app

### ISSUE THREAD

**Issue by drahnieR** [cerebroapp/cerebro#530]
- [ ] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 11.2.1
- **Cerebro.app version**: 0.4.0
- **Relevant information from devtools** N/A

## Issue
0.4.0 is released on github but doesn't have binaries/packed app attached, neither does https://cerebroapp.com/#download

**Comment by trkohler** [comment]
are there any recommendations for maintainers on how to build the app on ubuntu?

**Comment by sergiobonfiglio** [comment]
#544

**Comment by CelsoSantos** [comment]
How does one get the .app file on MacOS?? I've ran `yarn run package` and I do get some files output to the `/app/dist` directory, but they're not packaged as an .app. What am I missing?

**Comment by oguhpereira** [comment]
We will not generate binaries for version 0.4 because it is not working well.

https://github.com/cerebroapp/cerebro/releases/tag/v0.5.0

try using version 0.5 or an older version

note: some plugins are not working in v0.5 we will fix this soon

**Comment by f5-ericmarden** [comment]
FWIW, the v0.5.0 `*.AppImage` worked out of the box for me on RHEL9 ... where v0.3.1 had the pango/harbuzz too old error.
