### ISSUE TITLE
release .deb

### ISSUE THREAD

**Issue by DevKleber** [cerebroapp/cerebro#544]
Please release .deb

**Comment by sergiobonfiglio** [comment]
I don't think I can pull request a release but you can get it from this [fork](https://github.com/sergiobonfiglio/cerebro/releases/tag/v0.4.0)

**Comment by oguhpereira** [comment]
I created a new version with the releases for linux

https://github.com/cerebroapp/cerebro/releases/tag/v0.5.0

However some plugins stopped working in this version, we will investigate to fix that!
