### ISSUE TITLE
No Apps showimg up

### ISSUE THREAD

**Issue by Ftamino** [cerebroapp/cerebro#546]
- [x] I am on the [latest](https://github.com/sergiobonfiglio/cerebro/releases/tag/v0.4.0) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version amd Name**: Ubuntu 21.10 
- **Cerebro.app version**: 4.0 

## Issue
When im open up cerebro and search there are no apps showing up altoug i activate the applications plugin. Is there anyone how can help me because else cerebro is useless for me

**Comment by hugh-unicenta** [comment]
same here - on ubuntu 20.04. I've downloaded the sources and built the project same issue.

**Comment by DylanAkp** [comment]
Same here, from terminal 
Here is logs (valgrind doesn't show any issue, I don't know so much about AppImage)
`> ./cerebro-0.3.1-x86_64.AppImage
installed: X-AppImage-BuildId=4c9e08a0-909d-11a7-22a7-6ff87461f7d9 image: X-AppImage-BuildId=4c9e08a0-909d-11a7-22a7-6ff87461f7d9
[1]    10954 segmentation fault (core dumped)  ./cerebro-0.3.1-x86_64.AppImage`

**Comment by oguhpereira** [comment]
Thanks for the issue!

Unfortunately this problem is not the responsibility of the cerebro

with electron update the plugin https://github.com/KELiON/cerebro-tools stopped working. For now try to use an older version!
