### ISSUE TITLE
Incorrect version for release v0.4.0

### ISSUE THREAD

**Issue by gerardbosch** [cerebroapp/cerebro#547]
- [x] I am on the [latest](https://github.com/KELiON/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/KELiON/cerebro/issues) of this repo and believe that this is not a duplicate

- **Cerebro.app version**: 0.4.0

### 1. Incorrect version in `package.json`
```console
❯ git checkout v0.4.0
❯ grep version package.json  
  "version": "0.3.3",
❯ grep version app/package.json
  "version": "0.3.3",
```

Don't know much about  JS/Electron, so I'm not sure if more files need to be updated.

### 2. No AppImage available to download

I guess there should be a problem with the `v0.4.0` release as the AppImage binary is not available to download:
https://github.com/cerebroapp/cerebro/releases/tag/v0.4.0

Thanks for reviewing!

**Comment by imabp** [comment]
For fixing the package and creating AppImages follow these steps. @gerardbosch 

```bash
git clone https://github.com/cerebroapp/cerebro.git -b v0.4.0
```
```bash
cd cerebro
```

Replace the package version with 0.4.0 under `app/`
```
sed -i 's/"0.3.3"/"0.4.0"/g; s/^\( *"electron-updater": \)".*",$/\1"^4.0.0",/g' app/package.json

```

Replace the package version with 0.4.0 under `/` root directory of the repo.
```
sed -i 's/"0.3.3"/"0.4.0"/g; s/^\( *"build": .*yarn minify\)",$/\1 \&\& electron-builder",/g' package.json
```
Build the application from `app` dir
```
(yarn; cd app; yarn); yarn build
```

Once done, head over to `./release/` folder in root of the project directory,, you will find the AppImage
`./release/Cerebro-0.4.0.AppImage`

I guess that answers the query of AppImage. 
If you want to run the AppImage, read this stuff
[imabp/snippets](https://github.com/imabp/snippets/blob/main/AppImages_Ubuntu.md)

**Comment by asjur** [comment]
@imabp This seems to fail under VoidLinux with the following message:

`⨯ editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.  stackTrace=
                                                                                                          Error: editions-autoloader-none-broadened: Unable to determine a suitable edition, even after broadening.
`

**Comment by imabp** [comment]
@asjur, if you are an end user, who want to have such functionality. 😅
Please refer this: https://www.abirpal.dev/snippets/linux-productivity-handbook-for-developers?uuid=0b74fa62-d5ec-469b-843b-15b41db56ae0

**Comment by oguhpereira** [comment]
We're not going to continue with version 0.4, I've already adjusted it to version 0.5, thanks
