### ISSUE TITLE
Build error Can't resolve 'spawn-sync' 

### ISSUE THREAD

**Issue by ganjarpanji** [cerebroapp/cerebro#550]
- [X] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [X] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: macOS 12.2.1 M1 Pro
- **Cerebro.app version**: Checkout from master (https://github.com/cerebroapp/cerebro/commit/606a1ba6f83f6268510001f98fc864e5816b67b2)
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue
I got failed build error, tried to update manually `execa` as mentioned from here https://github.com/sindresorhus/shell-env/issues/12
```
WARNING in ./node_modules/shell-env/node_modules/cross-spawn/index.js
Module not found: Error: Can't resolve 'spawn-sync' in '/Users/me/Project/cerebro/node_modules/shell-env/node_modules/cross-spawn'
 @ ./node_modules/shell-env/node_modules/cross-spawn/index.js 32:26-47
 @ ./node_modules/shell-env/node_modules/execa/index.js
 @ ./node_modules/shell-env/index.js
 @ ./node_modules/shell-path/index.js
 @ ./node_modules/fix-path/index.js
 @ ./app/background/background.js
 @ multi webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr ./app/background/background

```

**Comment by JJgar2725** [comment]
Also ran into this error - installing spawn-sync by using `npm i spawn-sync` got rid of the error when compiling.

**Comment by tommisaltiola** [comment]
I got this on Fedora 36: `WARNING in ./node_modules/shell-env/node_modules/cross-spawn/index.js
Module not found: Error: Can't resolve 'spawn-sync' in '/home/tommi/cerebro/node_modules/shell-env/node_modules/cross-spawn'
 @ ./node_modules/shell-env/node_modules/cross-spawn/index.js 32:26-47
 @ ./node_modules/shell-env/node_modules/execa/index.js
 @ ./node_modules/shell-env/index.js
 @ ./node_modules/shell-path/index.js
 @ ./node_modules/fix-path/index.js
 @ ./app/background/background.js
 @ multi webpack-hot-middleware/client?path=http://localhost:3000/__webpack_hmr ./app/background/background
`
