### ISSUE TITLE
Cerebro not listing apps (linux OpenSuse)

### ISSUE THREAD

**Issue by richbai90** [cerebroapp/cerebro#555]
- [x ] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [ x] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name** OpenSuse Tumbleweed Release 20220413
- **Cerebro.app version**: 0.5.0 (App Image Version)
- **Relevant information from devtools** _(See above how to open it)_: After setting devtools on I selected the tray icon, launched Dev. tools (main) and nothing loaded 

![devtools](https://media.giphy.com/media/ePjMU1964X7IBnylbw/giphy.gif)

## Issue
Cerebro is not listing apps. Everything else works fine, but whenever I type an app name it comes up only with a google search. I've tried running with elevated permissions and and the --no-sandbox flag and that results in a crash. I've tried built-in applications, applications installed with the default package manager, and applications installed using snap. It's the same experience in each situation.

**Comment by HDV998** [comment]
same here, found any solution?

**Comment by champ7champ** [comment]
same on Manjaro
