### ISSUE TITLE
Unable to use Cerebro on KDE Plasma (Disappears on click.)

### ISSUE THREAD

**Issue by Syndrizzle** [cerebroapp/cerebro#556]
- [x] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS: Kubuntu 22.04 LTS**: 
- **Cerebro Version: 0.5.0**: 

## Issue
I am unable to use Cerebro on KDE, I tried to type the text using keyboard, that doesn't work, I tried to manually click it, that doesn't work either. Cerebro just completely disappears, whereas Ulauncher works completely fine with KDE. Please look into this, I cannot gather the dev logs since I cannot click the window :((

I have even tried changing the window rules but that doesn't help either!
![image](https://user-images.githubusercontent.com/96112833/164743625-b3138d2d-6718-45e6-b8ab-951f25aa8e69.png)
Below is a video of the issue:

https://user-images.githubusercontent.com/96112833/164743035-f3386eb7-2478-40bb-a7ab-d85d534e463c.mp4

**Comment by hatch01** [comment]
I have the same issue and tested all the versions since 0.5.0.

**Comment by d10r** [comment]
same here on Kubuntu 20.04 LTS

**Comment by hatch01** [comment]
I fixed it in this PR #640

**Comment by oguhpereira** [comment]
Can you validate from the last update?

**Comment by Ataraksia** [comment]
Can confirm.  I was having the same issues which made Cerebro completely unusable, but this change solved it completely, cheers.

**Comment by oguhpereira** [comment]
thanks for the feedback

**Comment by DraggonFantasy** [comment]
Happens to me on v0.11.0
