### ISSUE TITLE
how to connect elasticsearch with  https-ssl?

### ISSUE THREAD

**Issue by hmj589119** [cerebroapp/cerebro#560]
- [x] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: 5.4.185-200.el7.x86_64  CentOS Linux
- **Cerebro.app version**: cerebro-0.9.4-1.noarch
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue
        when connect to elasticsearch with https-ssl: 
        Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by hmj589119** [comment]
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by dubisdev** [comment]
Hi @hmj589119!
I think this is not the Cerebro you seem to be talking about. CerebroApp does not have any version like the one you mention nor is it directly related to elasticsearch (unless it is a plugin). Take a look at the [readme](https://github.com/cerebroapp/cerebro#readme) and please confirm if it is a bug in *this Cerebro*.

**Comment by hmj589119** [comment]
> Hi @hmj589119! I think this is not the Cerebro you seem to be talking about. CerebroApp does not have any version like the one you mention nor is it directly related to elasticsearch (unless it is a plugin). Take a look at the [readme](https://github.com/cerebroapp/cerebro#readme) and please confirm if it is a bug in _this Cerebro_.

Thanks, i have resolved this, by **import the ca.crt**; 
And the hosts setting like this: 
```
hosts = [
  {
    host = "https://192.168.15.33:9200"   
    name = "ELS Cluster"
    auth = {
      username = "elastic"
      password = "pepg0lxxxxxxXadjuxxx"
    }
  }
]
```

**Comment by stereon** [comment]
请问你怎么导入的ca.crt
