### ISSUE TITLE
SEARCHING MacOS MAINTAINER

### ISSUE THREAD

**Issue by dubisdev** [cerebroapp/cerebro#602]
Cerebro is ready for running in MacOS but we don't want to release packages if we can't test them.

We need someone who can actively test if Cerebro is working on this platform. This person doesn't need to develop nothing, just test, but it would be nice if him/herself has development knowledge so we can debug possible errors.

As a workaround for MacOS users, an executable can be created by following this steps:

1. Clone the repo - Using `git clone` or the GH client
2. Install dependencies - `yarn --force`
3. Package the app - `yarn package`
4. The executables are released to the `releases` folder.

**Comment by joh6nn** [comment]
I'm interested in helping with this

**Comment by ChFlick** [comment]
I'd also like to help here. I've got the same issue as in #607, the app won't show at all. Just to see what happens, I've tried locally checking out cerebro-ui and manually removing the places where `nodobjc` is used. The app starts, though there are still plenty of errors.
If help is wanted, I'd love to contribute.

**Comment by dubisdev** [comment]
Hi @ChFlick
Thanks for your help! I'll mention you in a new issue in the cerebro-ui repo with some info I think can be useful for solving the issue

**Comment by dubisdev** [comment]
I'm closing this for now as we have MacOS contributors helping to test Cerebro 🙌
