### ISSUE TITLE
a JAVASCRIPT eeror occured in main proccess 

### ISSUE THREAD

**Issue by Abolfazl-MI** [cerebroapp/cerebro#614]
hello to every one .this is my forst time want to try this cool application. I just donwloded appImage for installing on ubuntu but when I grant the access and run the program I face with this error

![image](https://user-images.githubusercontent.com/80602236/191977957-26e49c3a-8e06-40ed-b5de-f93f4f5288c5.png)

**Comment by dubisdev** [comment]
Hi Abolfazl

Could you please tell us:

- What is your OS version

- The Cerebro version you downloaded

- The steps so we can reproduce this issue


Thanks

**Comment by Abolfazl-MI** [comment]
Hi there I use Ubuntu last version 22.0.4
Cerbero version is 0.8.0 app image

**Comment by dubisdev** [comment]
Ok I just reproduced it. We need to update `@cerebroapp/cerebro-ui`. I would recommend you using [`v0.7.1`](https://github.com/cerebroapp/cerebro/releases/tag/v0.7.1) for now.
