### ISSUE TITLE
Cerebro not working on Fedora, it just shows the icon

### ISSUE THREAD

**Issue by edbanshee** [cerebroapp/cerebro#617]
- [x] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Fedora Linux 36 (Workstation Edition) (GNOME 42.4) (Wayland)
- **Cerebro.app version**: 0.8.0
- **Relevant information from devtools**: N/A

## Issue

When I run the latest AppImage executable, it runs and the Cerebro icon shows on my top bar, I can interact with it to open the menu, however thats all I can do. Whenever i click on Toggle Cerebro, nothing happens

I've ran the AppImage through the terminal, when it runs I get this:

```
$ ./Cerebro-0.8.0.AppImage 
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
```

Then again, the icon shows up and I can interact with the menu, but I get the following errors whenever I click on Toggle Cerebro, Plugins, or Preferences (Updates, Donate and Quit work fine):

> [13411:1011/185432.882995:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
> [13411:1011/185436.648985:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!

If i click again, i get the same, just with a 3 times. And thats it, if i click again, the counter no longer goes up, it stops at 3 but still nothing works

**Comment by dubisdev** [comment]
Hi @edbanshee and thanks for your report!

We are having issues with one of our dependencies in the latest version of Cerebro.

A PR (#616) that might fix this is waiting a review. For now the best option is to get the previous version [(0.7.1)](https://github.com/cerebroapp/cerebro/releases/tag/v0.7.1)

Please, give it a try and if the error persists we will try to reproduce it.

**Comment by edbanshee** [comment]
The older version works fine, thank you. Then i only had bad timing discovering Cerebro on the current version
