### ISSUE TITLE
Javascript Error: lastShownDonateDialog must be number

### ISSUE THREAD

**Issue by heywoodlh** [cerebroapp/cerebro#624]
- [x] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Windows 11 Pro 22621.819
- **Cerebro.app version**: 0.9.0
- **Relevant information from devtools**: The app won't launch for me at all so I can't really open the dev tools... :D

## Issue:

When launching the Cerebro executable on Windows 11, I encounter the following error which seems to cause Cerebro to fail to launch:
![image](https://user-images.githubusercontent.com/18178614/201225155-70d9bcb4-f802-401a-ba94-5d4ee22c176d.png)

The other Javascript errors in the Github Issues look similar but don't seem to be related to this `lastShownDonateDialog` error. 

## Unrelated:

Just discovered Cerebro today, very excited for the possibility of a cross-platform launcher (I'm normally on NixOS but sometimes am on MacOS and Windows). Thanks for making a cross-platform launcher! Will happily donate once I've actually implemented Cerebro in my workflows.

**Comment by dubisdev** [comment]
Hi @heywoodlh thanks for your report!

It seems like an error with the config validator. I'll investigate It!

**Comment by dubisdev** [comment]
Hi again @heywoodlh !

I have tried to reproduce the issue but I wasn't able to do it. I am also a Win11 user, I deleted all the program files, installed from 0 and the program works for me.

Maybe you have manually changed the `config.json` file?

In Windows you can find this file in `~\AppData\Roaming\Cerebro`. As a solution, you can follow the next steps:

1. Exit from Cerebro
2. Go to `~\AppData\Roaming\Cerebro` in the file explorer
3. Delete config.json file
4. Start Cerebro

This should create a new config file without errors.

I hope this fixes your error. Let me know it and, if not, please comment here the steps you have followed to get the error.

Thanks 🙌

**Comment by oguhpereira** [comment]
Hello, we no longer have the donate dialog, can you test it in our latest version?

**Comment by collioud** [comment]
For information, I have the same issue with the 0.10.0 version on Linux (Ubuntu 20.04) using the deb package or the appimage. See below the command line output.

```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Config schema violation: `lastShownDonateDialog` must be number
    at e.exports._validate (/tmp/.mount_Cerebr4dQaNN/resources/app.asar/main.js:2:45448)
    at get store [as store] (/tmp/.mount_Cerebr4dQaNN/resources/app.asar/main.js:2:44169)
    at new T (/tmp/.mount_Cerebr4dQaNN/resources/app.asar/main.js:2:41902)
    at new e.exports (/tmp/.mount_Cerebr4dQaNN/resources/app.asar/main.js:8:31842)
    at 9641 (/tmp/.mount_Cerebr4dQaNN/resources/app.asar/main.js:2:30510)
    at r (/tmp/.mount_Cerebr4dQaNN/resources/app.asar/main.js:8:68066)
    at /tmp/.mount_Cerebr4dQaNN/resources/app.asar/main.js:8:68576
    at Object.<anonymous> (/tmp/.mount_Cerebr4dQaNN/resources/app.asar/main.js:8:68602)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1175:10)

```

**Comment by oguhpereira** [comment]
we just removed this dialog in version 11, I think this problem may not occur anymore @collioud

**Comment by oguhpereira** [comment]
I will close here, if something similar happens please report
