### ISSUE TITLE
Select-all shortcut (CMD-a) is not working on Mac

### ISSUE THREAD

**Issue by borondics** [cerebroapp/cerebro#628]
- [x] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**:  MacOS Monterey 12.6
- **Cerebro.app version**:  0.9
- **Relevant information from devtools** _(See above how to open it)_: 

## Issue

The **CMD-a** shortcut to select all text is not working in the Cerebro window. If this is not a bug it would be a very useful addition.

**Comment by dubisdev** [comment]
Hi @borondics, We are working to implement this 🙌

This will be released in the next version

Thanks for your feedback 😉
