### ISSUE TITLE
Plugins don't want to install

### ISSUE THREAD

**Issue by mathe00** [cerebroapp/cerebro#636]
- [x] I am on the [latest](https://github.com/cerebroapp/cerebro/releases/latest) Cerebro.app version
- [x] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

- **OS version and name**: Linux Mint 21 Cinnamon
- **Cerebro.app version**: the last version

---

While writing this request, I discovered the existence of the developer mode and discovered the error that occurs when I want to install a plugin, this should help you

Screenshot :

![image](https://user-images.githubusercontent.com/97852395/206274429-bbffaab0-0047-46c3-8d0f-2c89766b5332.png)

Thanks to the one who will answer me :pray:

**Comment by dubisdev** [comment]
Hi @mathe00 and thanks for your report.

Does this error appear in all plugin installations or only in this particular one?

**Comment by mathe00** [comment]
Hello @dubisdev , this error appears for all plugins. And I can't use any plugin. Not even the basic ones. I can just quit cerebro or access the settings.

I just tested on my chromebook and everything works fine on it.

I forgot to mention that I installed Cerebro via .deb (even if I tried older versions or other ways)

**Comment by dubisdev** [comment]
I'll investigate on this, thanks

**Comment by dubisdev** [comment]
I just opened a PR with some changes that should fix this issue. We will release a new version as soon as this PR is merged.
