### ISSUE TITLE
Just a quick heads up about broken links

### ISSUE THREAD

**Issue by svallory** [cerebroapp/cerebro#645]
- [x] I have searched the [issues](https://github.com/cerebroapp/cerebro/issues) of this repo and believe that this is not a duplicate

[cerebroapp.com](https://cerebroapp.com/ ) download links point to version `0.3.1`

Also, there's no deployment for the link in the "about" section of the repository: [cerebroapp.vercel.app](https://cerebroapp.vercel.app/)

**Comment by oguhpereira** [comment]
Thank you for notifying us, we will update the site soon.
