### ISSUE TITLE
Where can I donate?

### ISSUE THREAD

**Issue by luizcieslak** [cerebroapp/cerebro#652]
Hi! This app is awesome and I want to contribute in some way. 

I notice the https://www.cerebroapp.com/#donate link is broken. Do you currently have a way to receive donations or have considered using GitHub Sponsors?

**Comment by oguhpereira** [comment]
Glad you liked the app. I am very happy that you are using it and that you want to make a donation. For now we are revamping the donation process.

Follow our twitter and help us with the evangelization of the project

**Comment by luizcieslak** [comment]
Sounds good! Will keep an 👀
