### ISSUE TITLE
feat: order results by most selected

### ISSUE THREAD

**Issue by maximbaz** [cerebroapp/cerebro#91]
I'd like Cerebro to remember which apps I open most often. It doesn't have to rely on OS to provide this knowledge, we could gather this information by ourselves. 

A simple idea: extend `apps_cache.json` with a counter of how many times this app was opened via Cerebro. Then use this counter to sort the list of results (items with higher counter go up, items with identical counter are sorted alphabetically).

That way, for example, assuming that I start "Chrome" many times a day, after a while the Chrome will be the first item in the results list right after I type "c".

**Comment by AlexAlabyev** [comment]
@maximbaz that's a good idea you're proposing. It might reduce the amount of character you have to type in before you get what you need.

**Comment by andylima** [comment]
+1 for this. & this would be great also for files. As in: I'd like Cerebro to remember which files I open most often. :)

**Comment by Kageetai** [comment]
keypirinha has this nicely implemented in my opinion and uses a kind of ranking system each time you select an item. Unfortunately it is not really explained in the documentation: http://keypirinha.com/first.html#associate-a-keyword-to-an-item
What I mean, it's not just a counter, but a bit more sophisticated

**Comment by LuckyLukert** [comment]
Right now, this feature works. But every time you restart cerebro, the priority-list is cleared. That could be improved as suggested by maximbaz.

Thanks

**Comment by jonnyasmar** [comment]
Yep, this feature has been available on Launchy (Windows) for years now. Kind of defeats the purpose for the list to be cleared. Is there an impediment to that? Seems like an easy fix.

**Comment by oguhpereira** [comment]
There are 2 issues that talk about ordering the items we will follow with them
