### ISSUE TITLE
No desktop entries on Ubuntu 16.04

### ISSUE THREAD

**Issue by chopfitzroy** [cerebroapp/cerebro#96]
Hey just tried installing the new build on my work PC running Ubuntu 16.04, first tried the `.deb` installer which only rendered a white box when toggling which would not recieve any input.

Next up I tried the `AppImage` which did render a usable input but when searching no desktop entries were found.

Please let me know what information I can provide to help debug.

Cheers.

**Comment by KELiON** [comment]
@CrashyBang hey! Can you try to turn on developer mode in preferences and after that run tray menu → development → DevTools (background), reload app (tray menu → development → reload) and check if you have any errors in console?

**Comment by CrashyBang** [comment]
Hey @KELiON just tried it at home and it is working fine so will have to try the above at work tomorrow.

Cheers.

**Comment by KELiON** [comment]
@CrashyBang hey! Did you try it one more time?

**Comment by CrashyBang** [comment]
Hey @KELiON sorry it is on my work PC I will try to get to it tomorrow my apologies.

**Comment by SurPaul** [comment]
I have the same problem. Terminal does not show anything. "Plugins" and "Preferences..." don't work

**Comment by KELiON** [comment]
@SurPaul so, you just don't have search input? Or you don't see results?

**Comment by SurPaul** [comment]
@KELiON Александр, так вы русский... Белое поле только есть, больше ничего. "a white box when toggling which would not receive any input". I got an update 0.2.7-4 today. Nothing's changed.

**Comment by dubisdev** [comment]
I'm closing this issue as outdated. Please, try the new version (v0.7.1) and open a new issue if the problem persists.
